// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/clinic"
	"github.com/Alijeyrad/simorq_backend/internal/repo/clinicpermission"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/Alijeyrad/simorq_backend/internal/repo/user"
	"github.com/google/uuid"
)

// ClinicPermissionUpdate is the builder for updating ClinicPermission entities.
type ClinicPermissionUpdate struct {
	config
	hooks    []Hook
	mutation *ClinicPermissionMutation
}

// Where appends a list predicates to the ClinicPermissionUpdate builder.
func (_u *ClinicPermissionUpdate) Where(ps ...predicate.ClinicPermission) *ClinicPermissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *ClinicPermissionUpdate) SetClinicID(v uuid.UUID) *ClinicPermissionUpdate {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *ClinicPermissionUpdate) SetNillableClinicID(v *uuid.UUID) *ClinicPermissionUpdate {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ClinicPermissionUpdate) SetUserID(v uuid.UUID) *ClinicPermissionUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ClinicPermissionUpdate) SetNillableUserID(v *uuid.UUID) *ClinicPermissionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ClinicPermissionUpdate) SetResourceType(v string) *ClinicPermissionUpdate {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ClinicPermissionUpdate) SetNillableResourceType(v *string) *ClinicPermissionUpdate {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ClinicPermissionUpdate) SetResourceID(v uuid.UUID) *ClinicPermissionUpdate {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ClinicPermissionUpdate) SetNillableResourceID(v *uuid.UUID) *ClinicPermissionUpdate {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *ClinicPermissionUpdate) ClearResourceID() *ClinicPermissionUpdate {
	_u.mutation.ClearResourceID()
	return _u
}

// SetAction sets the "action" field.
func (_u *ClinicPermissionUpdate) SetAction(v string) *ClinicPermissionUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ClinicPermissionUpdate) SetNillableAction(v *string) *ClinicPermissionUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetGranted sets the "granted" field.
func (_u *ClinicPermissionUpdate) SetGranted(v bool) *ClinicPermissionUpdate {
	_u.mutation.SetGranted(v)
	return _u
}

// SetNillableGranted sets the "granted" field if the given value is not nil.
func (_u *ClinicPermissionUpdate) SetNillableGranted(v *bool) *ClinicPermissionUpdate {
	if v != nil {
		_u.SetGranted(*v)
	}
	return _u
}

// SetClinic sets the "clinic" edge to the Clinic entity.
func (_u *ClinicPermissionUpdate) SetClinic(v *Clinic) *ClinicPermissionUpdate {
	return _u.SetClinicID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ClinicPermissionUpdate) SetUser(v *User) *ClinicPermissionUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ClinicPermissionMutation object of the builder.
func (_u *ClinicPermissionUpdate) Mutation() *ClinicPermissionMutation {
	return _u.mutation
}

// ClearClinic clears the "clinic" edge to the Clinic entity.
func (_u *ClinicPermissionUpdate) ClearClinic() *ClinicPermissionUpdate {
	_u.mutation.ClearClinic()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ClinicPermissionUpdate) ClearUser() *ClinicPermissionUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ClinicPermissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClinicPermissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ClinicPermissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClinicPermissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClinicPermissionUpdate) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := clinicpermission.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`repo: validator failed for field "ClinicPermission.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := clinicpermission.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`repo: validator failed for field "ClinicPermission.action": %w`, err)}
		}
	}
	if _u.mutation.ClinicCleared() && len(_u.mutation.ClinicIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "ClinicPermission.clinic"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "ClinicPermission.user"`)
	}
	return nil
}

func (_u *ClinicPermissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clinicpermission.Table, clinicpermission.Columns, sqlgraph.NewFieldSpec(clinicpermission.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(clinicpermission.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(clinicpermission.FieldResourceID, field.TypeUUID, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(clinicpermission.FieldResourceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(clinicpermission.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Granted(); ok {
		_spec.SetField(clinicpermission.FieldGranted, field.TypeBool, value)
	}
	if _u.mutation.ClinicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clinicpermission.ClinicTable,
			Columns: []string{clinicpermission.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClinicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clinicpermission.ClinicTable,
			Columns: []string{clinicpermission.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   clinicpermission.UserTable,
			Columns: []string{clinicpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   clinicpermission.UserTable,
			Columns: []string{clinicpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clinicpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ClinicPermissionUpdateOne is the builder for updating a single ClinicPermission entity.
type ClinicPermissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ClinicPermissionMutation
}

// SetClinicID sets the "clinic_id" field.
func (_u *ClinicPermissionUpdateOne) SetClinicID(v uuid.UUID) *ClinicPermissionUpdateOne {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *ClinicPermissionUpdateOne) SetNillableClinicID(v *uuid.UUID) *ClinicPermissionUpdateOne {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *ClinicPermissionUpdateOne) SetUserID(v uuid.UUID) *ClinicPermissionUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *ClinicPermissionUpdateOne) SetNillableUserID(v *uuid.UUID) *ClinicPermissionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetResourceType sets the "resource_type" field.
func (_u *ClinicPermissionUpdateOne) SetResourceType(v string) *ClinicPermissionUpdateOne {
	_u.mutation.SetResourceType(v)
	return _u
}

// SetNillableResourceType sets the "resource_type" field if the given value is not nil.
func (_u *ClinicPermissionUpdateOne) SetNillableResourceType(v *string) *ClinicPermissionUpdateOne {
	if v != nil {
		_u.SetResourceType(*v)
	}
	return _u
}

// SetResourceID sets the "resource_id" field.
func (_u *ClinicPermissionUpdateOne) SetResourceID(v uuid.UUID) *ClinicPermissionUpdateOne {
	_u.mutation.SetResourceID(v)
	return _u
}

// SetNillableResourceID sets the "resource_id" field if the given value is not nil.
func (_u *ClinicPermissionUpdateOne) SetNillableResourceID(v *uuid.UUID) *ClinicPermissionUpdateOne {
	if v != nil {
		_u.SetResourceID(*v)
	}
	return _u
}

// ClearResourceID clears the value of the "resource_id" field.
func (_u *ClinicPermissionUpdateOne) ClearResourceID() *ClinicPermissionUpdateOne {
	_u.mutation.ClearResourceID()
	return _u
}

// SetAction sets the "action" field.
func (_u *ClinicPermissionUpdateOne) SetAction(v string) *ClinicPermissionUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ClinicPermissionUpdateOne) SetNillableAction(v *string) *ClinicPermissionUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetGranted sets the "granted" field.
func (_u *ClinicPermissionUpdateOne) SetGranted(v bool) *ClinicPermissionUpdateOne {
	_u.mutation.SetGranted(v)
	return _u
}

// SetNillableGranted sets the "granted" field if the given value is not nil.
func (_u *ClinicPermissionUpdateOne) SetNillableGranted(v *bool) *ClinicPermissionUpdateOne {
	if v != nil {
		_u.SetGranted(*v)
	}
	return _u
}

// SetClinic sets the "clinic" edge to the Clinic entity.
func (_u *ClinicPermissionUpdateOne) SetClinic(v *Clinic) *ClinicPermissionUpdateOne {
	return _u.SetClinicID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_u *ClinicPermissionUpdateOne) SetUser(v *User) *ClinicPermissionUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the ClinicPermissionMutation object of the builder.
func (_u *ClinicPermissionUpdateOne) Mutation() *ClinicPermissionMutation {
	return _u.mutation
}

// ClearClinic clears the "clinic" edge to the Clinic entity.
func (_u *ClinicPermissionUpdateOne) ClearClinic() *ClinicPermissionUpdateOne {
	_u.mutation.ClearClinic()
	return _u
}

// ClearUser clears the "user" edge to the User entity.
func (_u *ClinicPermissionUpdateOne) ClearUser() *ClinicPermissionUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the ClinicPermissionUpdate builder.
func (_u *ClinicPermissionUpdateOne) Where(ps ...predicate.ClinicPermission) *ClinicPermissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ClinicPermissionUpdateOne) Select(field string, fields ...string) *ClinicPermissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ClinicPermission entity.
func (_u *ClinicPermissionUpdateOne) Save(ctx context.Context) (*ClinicPermission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ClinicPermissionUpdateOne) SaveX(ctx context.Context) *ClinicPermission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ClinicPermissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ClinicPermissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ClinicPermissionUpdateOne) check() error {
	if v, ok := _u.mutation.ResourceType(); ok {
		if err := clinicpermission.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`repo: validator failed for field "ClinicPermission.resource_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Action(); ok {
		if err := clinicpermission.ActionValidator(v); err != nil {
			return &ValidationError{Name: "action", err: fmt.Errorf(`repo: validator failed for field "ClinicPermission.action": %w`, err)}
		}
	}
	if _u.mutation.ClinicCleared() && len(_u.mutation.ClinicIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "ClinicPermission.clinic"`)
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "ClinicPermission.user"`)
	}
	return nil
}

func (_u *ClinicPermissionUpdateOne) sqlSave(ctx context.Context) (_node *ClinicPermission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(clinicpermission.Table, clinicpermission.Columns, sqlgraph.NewFieldSpec(clinicpermission.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`repo: missing "ClinicPermission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, clinicpermission.FieldID)
		for _, f := range fields {
			if !clinicpermission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("repo: invalid field %q for query", f)}
			}
			if f != clinicpermission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ResourceType(); ok {
		_spec.SetField(clinicpermission.FieldResourceType, field.TypeString, value)
	}
	if value, ok := _u.mutation.ResourceID(); ok {
		_spec.SetField(clinicpermission.FieldResourceID, field.TypeUUID, value)
	}
	if _u.mutation.ResourceIDCleared() {
		_spec.ClearField(clinicpermission.FieldResourceID, field.TypeUUID)
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(clinicpermission.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.Granted(); ok {
		_spec.SetField(clinicpermission.FieldGranted, field.TypeBool, value)
	}
	if _u.mutation.ClinicCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clinicpermission.ClinicTable,
			Columns: []string{clinicpermission.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ClinicIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   clinicpermission.ClinicTable,
			Columns: []string{clinicpermission.ClinicColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinic.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   clinicpermission.UserTable,
			Columns: []string{clinicpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   clinicpermission.UserTable,
			Columns: []string{clinicpermission.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ClinicPermission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{clinicpermission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
