// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/contactmessage"
	"github.com/google/uuid"
)

// ContactMessageCreate is the builder for creating a ContactMessage entity.
type ContactMessageCreate struct {
	config
	mutation *ContactMessageMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContactMessageCreate) SetCreatedAt(v time.Time) *ContactMessageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContactMessageCreate) SetNillableCreatedAt(v *time.Time) *ContactMessageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ContactMessageCreate) SetName(v string) *ContactMessageCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetEmail sets the "email" field.
func (_c *ContactMessageCreate) SetEmail(v string) *ContactMessageCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetSubject sets the "subject" field.
func (_c *ContactMessageCreate) SetSubject(v string) *ContactMessageCreate {
	_c.mutation.SetSubject(v)
	return _c
}

// SetMessage sets the "message" field.
func (_c *ContactMessageCreate) SetMessage(v string) *ContactMessageCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetID sets the "id" field.
func (_c *ContactMessageCreate) SetID(v uuid.UUID) *ContactMessageCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ContactMessageCreate) SetNillableID(v *uuid.UUID) *ContactMessageCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the ContactMessageMutation object of the builder.
func (_c *ContactMessageCreate) Mutation() *ContactMessageMutation {
	return _c.mutation
}

// Save creates the ContactMessage in the database.
func (_c *ContactMessageCreate) Save(ctx context.Context) (*ContactMessage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContactMessageCreate) SaveX(ctx context.Context) *ContactMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContactMessageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContactMessageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContactMessageCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := contactmessage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := contactmessage.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContactMessageCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`repo: missing required field "ContactMessage.created_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`repo: missing required field "ContactMessage.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := contactmessage.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`repo: validator failed for field "ContactMessage.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`repo: missing required field "ContactMessage.email"`)}
	}
	if v, ok := _c.mutation.Email(); ok {
		if err := contactmessage.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`repo: validator failed for field "ContactMessage.email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`repo: missing required field "ContactMessage.subject"`)}
	}
	if v, ok := _c.mutation.Subject(); ok {
		if err := contactmessage.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`repo: validator failed for field "ContactMessage.subject": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`repo: missing required field "ContactMessage.message"`)}
	}
	return nil
}

func (_c *ContactMessageCreate) sqlSave(ctx context.Context) (*ContactMessage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContactMessageCreate) createSpec() (*ContactMessage, *sqlgraph.CreateSpec) {
	var (
		_node = &ContactMessage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(contactmessage.Table, sqlgraph.NewFieldSpec(contactmessage.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(contactmessage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(contactmessage.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(contactmessage.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.Subject(); ok {
		_spec.SetField(contactmessage.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(contactmessage.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	return _node, _spec
}

// ContactMessageCreateBulk is the builder for creating many ContactMessage entities in bulk.
type ContactMessageCreateBulk struct {
	config
	err      error
	builders []*ContactMessageCreate
}

// Save creates the ContactMessage entities in the database.
func (_c *ContactMessageCreateBulk) Save(ctx context.Context) ([]*ContactMessage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ContactMessage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContactMessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContactMessageCreateBulk) SaveX(ctx context.Context) []*ContactMessage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContactMessageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContactMessageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
