// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/internprofile"
	"github.com/google/uuid"
)

// InternProfileCreate is the builder for creating a InternProfile entity.
type InternProfileCreate struct {
	config
	mutation *InternProfileMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *InternProfileCreate) SetCreatedAt(v time.Time) *InternProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *InternProfileCreate) SetNillableCreatedAt(v *time.Time) *InternProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *InternProfileCreate) SetUpdatedAt(v time.Time) *InternProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *InternProfileCreate) SetNillableUpdatedAt(v *time.Time) *InternProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetClinicMemberID sets the "clinic_member_id" field.
func (_c *InternProfileCreate) SetClinicMemberID(v uuid.UUID) *InternProfileCreate {
	_c.mutation.SetClinicMemberID(v)
	return _c
}

// SetInternshipYear sets the "internship_year" field.
func (_c *InternProfileCreate) SetInternshipYear(v int) *InternProfileCreate {
	_c.mutation.SetInternshipYear(v)
	return _c
}

// SetNillableInternshipYear sets the "internship_year" field if the given value is not nil.
func (_c *InternProfileCreate) SetNillableInternshipYear(v *int) *InternProfileCreate {
	if v != nil {
		_c.SetInternshipYear(*v)
	}
	return _c
}

// SetSupervisorIds sets the "supervisor_ids" field.
func (_c *InternProfileCreate) SetSupervisorIds(v []uuid.UUID) *InternProfileCreate {
	_c.mutation.SetSupervisorIds(v)
	return _c
}

// SetID sets the "id" field.
func (_c *InternProfileCreate) SetID(v uuid.UUID) *InternProfileCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *InternProfileCreate) SetNillableID(v *uuid.UUID) *InternProfileCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the InternProfileMutation object of the builder.
func (_c *InternProfileCreate) Mutation() *InternProfileMutation {
	return _c.mutation
}

// Save creates the InternProfile in the database.
func (_c *InternProfileCreate) Save(ctx context.Context) (*InternProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *InternProfileCreate) SaveX(ctx context.Context) *InternProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InternProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InternProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *InternProfileCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := internprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := internprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := internprofile.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *InternProfileCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`repo: missing required field "InternProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`repo: missing required field "InternProfile.updated_at"`)}
	}
	if _, ok := _c.mutation.ClinicMemberID(); !ok {
		return &ValidationError{Name: "clinic_member_id", err: errors.New(`repo: missing required field "InternProfile.clinic_member_id"`)}
	}
	return nil
}

func (_c *InternProfileCreate) sqlSave(ctx context.Context) (*InternProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *InternProfileCreate) createSpec() (*InternProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &InternProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(internprofile.Table, sqlgraph.NewFieldSpec(internprofile.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(internprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(internprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClinicMemberID(); ok {
		_spec.SetField(internprofile.FieldClinicMemberID, field.TypeUUID, value)
		_node.ClinicMemberID = value
	}
	if value, ok := _c.mutation.InternshipYear(); ok {
		_spec.SetField(internprofile.FieldInternshipYear, field.TypeInt, value)
		_node.InternshipYear = &value
	}
	if value, ok := _c.mutation.SupervisorIds(); ok {
		_spec.SetField(internprofile.FieldSupervisorIds, field.TypeJSON, value)
		_node.SupervisorIds = value
	}
	return _node, _spec
}

// InternProfileCreateBulk is the builder for creating many InternProfile entities in bulk.
type InternProfileCreateBulk struct {
	config
	err      error
	builders []*InternProfileCreate
}

// Save creates the InternProfile entities in the database.
func (_c *InternProfileCreateBulk) Save(ctx context.Context) ([]*InternProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*InternProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InternProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *InternProfileCreateBulk) SaveX(ctx context.Context) []*InternProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *InternProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *InternProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
