// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/internpatientaccess"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
)

// InternPatientAccessDelete is the builder for deleting a InternPatientAccess entity.
type InternPatientAccessDelete struct {
	config
	hooks    []Hook
	mutation *InternPatientAccessMutation
}

// Where appends a list predicates to the InternPatientAccessDelete builder.
func (_d *InternPatientAccessDelete) Where(ps ...predicate.InternPatientAccess) *InternPatientAccessDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *InternPatientAccessDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InternPatientAccessDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *InternPatientAccessDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(internpatientaccess.Table, sqlgraph.NewFieldSpec(internpatientaccess.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// InternPatientAccessDeleteOne is the builder for deleting a single InternPatientAccess entity.
type InternPatientAccessDeleteOne struct {
	_d *InternPatientAccessDelete
}

// Where appends a list predicates to the InternPatientAccessDelete builder.
func (_d *InternPatientAccessDeleteOne) Where(ps ...predicate.InternPatientAccess) *InternPatientAccessDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *InternPatientAccessDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{internpatientaccess.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *InternPatientAccessDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
