// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/interntask"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/google/uuid"
)

// InternTaskUpdate is the builder for updating InternTask entities.
type InternTaskUpdate struct {
	config
	hooks    []Hook
	mutation *InternTaskMutation
}

// Where appends a list predicates to the InternTaskUpdate builder.
func (_u *InternTaskUpdate) Where(ps ...predicate.InternTask) *InternTaskUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *InternTaskUpdate) SetClinicID(v uuid.UUID) *InternTaskUpdate {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableClinicID(v *uuid.UUID) *InternTaskUpdate {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetInternID sets the "intern_id" field.
func (_u *InternTaskUpdate) SetInternID(v uuid.UUID) *InternTaskUpdate {
	_u.mutation.SetInternID(v)
	return _u
}

// SetNillableInternID sets the "intern_id" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableInternID(v *uuid.UUID) *InternTaskUpdate {
	if v != nil {
		_u.SetInternID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InternTaskUpdate) SetTitle(v string) *InternTaskUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableTitle(v *string) *InternTaskUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCaption sets the "caption" field.
func (_u *InternTaskUpdate) SetCaption(v string) *InternTaskUpdate {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableCaption(v *string) *InternTaskUpdate {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *InternTaskUpdate) ClearCaption() *InternTaskUpdate {
	_u.mutation.ClearCaption()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InternTaskUpdate) SetSubmittedAt(v time.Time) *InternTaskUpdate {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableSubmittedAt(v *time.Time) *InternTaskUpdate {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetReviewStatus sets the "review_status" field.
func (_u *InternTaskUpdate) SetReviewStatus(v interntask.ReviewStatus) *InternTaskUpdate {
	_u.mutation.SetReviewStatus(v)
	return _u
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableReviewStatus(v *interntask.ReviewStatus) *InternTaskUpdate {
	if v != nil {
		_u.SetReviewStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *InternTaskUpdate) SetReviewedBy(v uuid.UUID) *InternTaskUpdate {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableReviewedBy(v *uuid.UUID) *InternTaskUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *InternTaskUpdate) ClearReviewedBy() *InternTaskUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewComment sets the "review_comment" field.
func (_u *InternTaskUpdate) SetReviewComment(v string) *InternTaskUpdate {
	_u.mutation.SetReviewComment(v)
	return _u
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableReviewComment(v *string) *InternTaskUpdate {
	if v != nil {
		_u.SetReviewComment(*v)
	}
	return _u
}

// ClearReviewComment clears the value of the "review_comment" field.
func (_u *InternTaskUpdate) ClearReviewComment() *InternTaskUpdate {
	_u.mutation.ClearReviewComment()
	return _u
}

// SetGrade sets the "grade" field.
func (_u *InternTaskUpdate) SetGrade(v string) *InternTaskUpdate {
	_u.mutation.SetGrade(v)
	return _u
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableGrade(v *string) *InternTaskUpdate {
	if v != nil {
		_u.SetGrade(*v)
	}
	return _u
}

// ClearGrade clears the value of the "grade" field.
func (_u *InternTaskUpdate) ClearGrade() *InternTaskUpdate {
	_u.mutation.ClearGrade()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *InternTaskUpdate) SetReviewedAt(v time.Time) *InternTaskUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *InternTaskUpdate) SetNillableReviewedAt(v *time.Time) *InternTaskUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *InternTaskUpdate) ClearReviewedAt() *InternTaskUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// Mutation returns the InternTaskMutation object of the builder.
func (_u *InternTaskUpdate) Mutation() *InternTaskMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *InternTaskUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InternTaskUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *InternTaskUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InternTaskUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InternTaskUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := interntask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`repo: validator failed for field "InternTask.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewStatus(); ok {
		if err := interntask.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`repo: validator failed for field "InternTask.review_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Grade(); ok {
		if err := interntask.GradeValidator(v); err != nil {
			return &ValidationError{Name: "grade", err: fmt.Errorf(`repo: validator failed for field "InternTask.grade": %w`, err)}
		}
	}
	return nil
}

func (_u *InternTaskUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(interntask.Table, interntask.Columns, sqlgraph.NewFieldSpec(interntask.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClinicID(); ok {
		_spec.SetField(interntask.FieldClinicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.InternID(); ok {
		_spec.SetField(interntask.FieldInternID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(interntask.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(interntask.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(interntask.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(interntask.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewStatus(); ok {
		_spec.SetField(interntask.FieldReviewStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(interntask.FieldReviewedBy, field.TypeUUID, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(interntask.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ReviewComment(); ok {
		_spec.SetField(interntask.FieldReviewComment, field.TypeString, value)
	}
	if _u.mutation.ReviewCommentCleared() {
		_spec.ClearField(interntask.FieldReviewComment, field.TypeString)
	}
	if value, ok := _u.mutation.Grade(); ok {
		_spec.SetField(interntask.FieldGrade, field.TypeString, value)
	}
	if _u.mutation.GradeCleared() {
		_spec.ClearField(interntask.FieldGrade, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(interntask.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(interntask.FieldReviewedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interntask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// InternTaskUpdateOne is the builder for updating a single InternTask entity.
type InternTaskUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *InternTaskMutation
}

// SetClinicID sets the "clinic_id" field.
func (_u *InternTaskUpdateOne) SetClinicID(v uuid.UUID) *InternTaskUpdateOne {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableClinicID(v *uuid.UUID) *InternTaskUpdateOne {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetInternID sets the "intern_id" field.
func (_u *InternTaskUpdateOne) SetInternID(v uuid.UUID) *InternTaskUpdateOne {
	_u.mutation.SetInternID(v)
	return _u
}

// SetNillableInternID sets the "intern_id" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableInternID(v *uuid.UUID) *InternTaskUpdateOne {
	if v != nil {
		_u.SetInternID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *InternTaskUpdateOne) SetTitle(v string) *InternTaskUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableTitle(v *string) *InternTaskUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetCaption sets the "caption" field.
func (_u *InternTaskUpdateOne) SetCaption(v string) *InternTaskUpdateOne {
	_u.mutation.SetCaption(v)
	return _u
}

// SetNillableCaption sets the "caption" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableCaption(v *string) *InternTaskUpdateOne {
	if v != nil {
		_u.SetCaption(*v)
	}
	return _u
}

// ClearCaption clears the value of the "caption" field.
func (_u *InternTaskUpdateOne) ClearCaption() *InternTaskUpdateOne {
	_u.mutation.ClearCaption()
	return _u
}

// SetSubmittedAt sets the "submitted_at" field.
func (_u *InternTaskUpdateOne) SetSubmittedAt(v time.Time) *InternTaskUpdateOne {
	_u.mutation.SetSubmittedAt(v)
	return _u
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableSubmittedAt(v *time.Time) *InternTaskUpdateOne {
	if v != nil {
		_u.SetSubmittedAt(*v)
	}
	return _u
}

// SetReviewStatus sets the "review_status" field.
func (_u *InternTaskUpdateOne) SetReviewStatus(v interntask.ReviewStatus) *InternTaskUpdateOne {
	_u.mutation.SetReviewStatus(v)
	return _u
}

// SetNillableReviewStatus sets the "review_status" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableReviewStatus(v *interntask.ReviewStatus) *InternTaskUpdateOne {
	if v != nil {
		_u.SetReviewStatus(*v)
	}
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *InternTaskUpdateOne) SetReviewedBy(v uuid.UUID) *InternTaskUpdateOne {
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableReviewedBy(v *uuid.UUID) *InternTaskUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *InternTaskUpdateOne) ClearReviewedBy() *InternTaskUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetReviewComment sets the "review_comment" field.
func (_u *InternTaskUpdateOne) SetReviewComment(v string) *InternTaskUpdateOne {
	_u.mutation.SetReviewComment(v)
	return _u
}

// SetNillableReviewComment sets the "review_comment" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableReviewComment(v *string) *InternTaskUpdateOne {
	if v != nil {
		_u.SetReviewComment(*v)
	}
	return _u
}

// ClearReviewComment clears the value of the "review_comment" field.
func (_u *InternTaskUpdateOne) ClearReviewComment() *InternTaskUpdateOne {
	_u.mutation.ClearReviewComment()
	return _u
}

// SetGrade sets the "grade" field.
func (_u *InternTaskUpdateOne) SetGrade(v string) *InternTaskUpdateOne {
	_u.mutation.SetGrade(v)
	return _u
}

// SetNillableGrade sets the "grade" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableGrade(v *string) *InternTaskUpdateOne {
	if v != nil {
		_u.SetGrade(*v)
	}
	return _u
}

// ClearGrade clears the value of the "grade" field.
func (_u *InternTaskUpdateOne) ClearGrade() *InternTaskUpdateOne {
	_u.mutation.ClearGrade()
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *InternTaskUpdateOne) SetReviewedAt(v time.Time) *InternTaskUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *InternTaskUpdateOne) SetNillableReviewedAt(v *time.Time) *InternTaskUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *InternTaskUpdateOne) ClearReviewedAt() *InternTaskUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// Mutation returns the InternTaskMutation object of the builder.
func (_u *InternTaskUpdateOne) Mutation() *InternTaskMutation {
	return _u.mutation
}

// Where appends a list predicates to the InternTaskUpdate builder.
func (_u *InternTaskUpdateOne) Where(ps ...predicate.InternTask) *InternTaskUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *InternTaskUpdateOne) Select(field string, fields ...string) *InternTaskUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated InternTask entity.
func (_u *InternTaskUpdateOne) Save(ctx context.Context) (*InternTask, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *InternTaskUpdateOne) SaveX(ctx context.Context) *InternTask {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *InternTaskUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *InternTaskUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *InternTaskUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := interntask.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`repo: validator failed for field "InternTask.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ReviewStatus(); ok {
		if err := interntask.ReviewStatusValidator(v); err != nil {
			return &ValidationError{Name: "review_status", err: fmt.Errorf(`repo: validator failed for field "InternTask.review_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Grade(); ok {
		if err := interntask.GradeValidator(v); err != nil {
			return &ValidationError{Name: "grade", err: fmt.Errorf(`repo: validator failed for field "InternTask.grade": %w`, err)}
		}
	}
	return nil
}

func (_u *InternTaskUpdateOne) sqlSave(ctx context.Context) (_node *InternTask, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(interntask.Table, interntask.Columns, sqlgraph.NewFieldSpec(interntask.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`repo: missing "InternTask.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, interntask.FieldID)
		for _, f := range fields {
			if !interntask.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("repo: invalid field %q for query", f)}
			}
			if f != interntask.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClinicID(); ok {
		_spec.SetField(interntask.FieldClinicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.InternID(); ok {
		_spec.SetField(interntask.FieldInternID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(interntask.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Caption(); ok {
		_spec.SetField(interntask.FieldCaption, field.TypeString, value)
	}
	if _u.mutation.CaptionCleared() {
		_spec.ClearField(interntask.FieldCaption, field.TypeString)
	}
	if value, ok := _u.mutation.SubmittedAt(); ok {
		_spec.SetField(interntask.FieldSubmittedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ReviewStatus(); ok {
		_spec.SetField(interntask.FieldReviewStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(interntask.FieldReviewedBy, field.TypeUUID, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(interntask.FieldReviewedBy, field.TypeUUID)
	}
	if value, ok := _u.mutation.ReviewComment(); ok {
		_spec.SetField(interntask.FieldReviewComment, field.TypeString, value)
	}
	if _u.mutation.ReviewCommentCleared() {
		_spec.ClearField(interntask.FieldReviewComment, field.TypeString)
	}
	if value, ok := _u.mutation.Grade(); ok {
		_spec.SetField(interntask.FieldGrade, field.TypeString, value)
	}
	if _u.mutation.GradeCleared() {
		_spec.ClearField(interntask.FieldGrade, field.TypeString)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(interntask.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(interntask.FieldReviewedAt, field.TypeTime)
	}
	_node = &InternTask{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{interntask.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
