// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/clinicmember"
	"github.com/Alijeyrad/simorq_backend/internal/repo/patient"
	"github.com/Alijeyrad/simorq_backend/internal/repo/patientprescription"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/google/uuid"
)

// PatientPrescriptionUpdate is the builder for updating PatientPrescription entities.
type PatientPrescriptionUpdate struct {
	config
	hooks    []Hook
	mutation *PatientPrescriptionMutation
}

// Where appends a list predicates to the PatientPrescriptionUpdate builder.
func (_u *PatientPrescriptionUpdate) Where(ps ...predicate.PatientPrescription) *PatientPrescriptionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PatientPrescriptionUpdate) SetUpdatedAt(v time.Time) *PatientPrescriptionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *PatientPrescriptionUpdate) SetPatientID(v uuid.UUID) *PatientPrescriptionUpdate {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillablePatientID(v *uuid.UUID) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *PatientPrescriptionUpdate) SetClinicID(v uuid.UUID) *PatientPrescriptionUpdate {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillableClinicID(v *uuid.UUID) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetTherapistID sets the "therapist_id" field.
func (_u *PatientPrescriptionUpdate) SetTherapistID(v uuid.UUID) *PatientPrescriptionUpdate {
	_u.mutation.SetTherapistID(v)
	return _u
}

// SetNillableTherapistID sets the "therapist_id" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillableTherapistID(v *uuid.UUID) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetTherapistID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PatientPrescriptionUpdate) SetTitle(v string) *PatientPrescriptionUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillableTitle(v *string) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *PatientPrescriptionUpdate) ClearTitle() *PatientPrescriptionUpdate {
	_u.mutation.ClearTitle()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PatientPrescriptionUpdate) SetNotes(v string) *PatientPrescriptionUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillableNotes(v *string) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PatientPrescriptionUpdate) ClearNotes() *PatientPrescriptionUpdate {
	_u.mutation.ClearNotes()
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *PatientPrescriptionUpdate) SetFileKey(v string) *PatientPrescriptionUpdate {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillableFileKey(v *string) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// ClearFileKey clears the value of the "file_key" field.
func (_u *PatientPrescriptionUpdate) ClearFileKey() *PatientPrescriptionUpdate {
	_u.mutation.ClearFileKey()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *PatientPrescriptionUpdate) SetFileName(v string) *PatientPrescriptionUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillableFileName(v *string) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *PatientPrescriptionUpdate) ClearFileName() *PatientPrescriptionUpdate {
	_u.mutation.ClearFileName()
	return _u
}

// SetPrescribedDate sets the "prescribed_date" field.
func (_u *PatientPrescriptionUpdate) SetPrescribedDate(v time.Time) *PatientPrescriptionUpdate {
	_u.mutation.SetPrescribedDate(v)
	return _u
}

// SetNillablePrescribedDate sets the "prescribed_date" field if the given value is not nil.
func (_u *PatientPrescriptionUpdate) SetNillablePrescribedDate(v *time.Time) *PatientPrescriptionUpdate {
	if v != nil {
		_u.SetPrescribedDate(*v)
	}
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *PatientPrescriptionUpdate) SetPatient(v *Patient) *PatientPrescriptionUpdate {
	return _u.SetPatientID(v.ID)
}

// SetTherapist sets the "therapist" edge to the ClinicMember entity.
func (_u *PatientPrescriptionUpdate) SetTherapist(v *ClinicMember) *PatientPrescriptionUpdate {
	return _u.SetTherapistID(v.ID)
}

// Mutation returns the PatientPrescriptionMutation object of the builder.
func (_u *PatientPrescriptionUpdate) Mutation() *PatientPrescriptionMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *PatientPrescriptionUpdate) ClearPatient() *PatientPrescriptionUpdate {
	_u.mutation.ClearPatient()
	return _u
}

// ClearTherapist clears the "therapist" edge to the ClinicMember entity.
func (_u *PatientPrescriptionUpdate) ClearTherapist() *PatientPrescriptionUpdate {
	_u.mutation.ClearTherapist()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PatientPrescriptionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatientPrescriptionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PatientPrescriptionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatientPrescriptionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PatientPrescriptionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := patientprescription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PatientPrescriptionUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := patientprescription.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`repo: validator failed for field "PatientPrescription.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := patientprescription.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`repo: validator failed for field "PatientPrescription.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := patientprescription.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`repo: validator failed for field "PatientPrescription.file_name": %w`, err)}
		}
	}
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientPrescription.patient"`)
	}
	if _u.mutation.TherapistCleared() && len(_u.mutation.TherapistIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientPrescription.therapist"`)
	}
	return nil
}

func (_u *PatientPrescriptionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(patientprescription.Table, patientprescription.Columns, sqlgraph.NewFieldSpec(patientprescription.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(patientprescription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClinicID(); ok {
		_spec.SetField(patientprescription.FieldClinicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(patientprescription.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(patientprescription.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(patientprescription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(patientprescription.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(patientprescription.FieldFileKey, field.TypeString, value)
	}
	if _u.mutation.FileKeyCleared() {
		_spec.ClearField(patientprescription.FieldFileKey, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(patientprescription.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(patientprescription.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.PrescribedDate(); ok {
		_spec.SetField(patientprescription.FieldPrescribedDate, field.TypeTime, value)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientprescription.PatientTable,
			Columns: []string{patientprescription.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientprescription.PatientTable,
			Columns: []string{patientprescription.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TherapistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientprescription.TherapistTable,
			Columns: []string{patientprescription.TherapistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TherapistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientprescription.TherapistTable,
			Columns: []string{patientprescription.TherapistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patientprescription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PatientPrescriptionUpdateOne is the builder for updating a single PatientPrescription entity.
type PatientPrescriptionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PatientPrescriptionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PatientPrescriptionUpdateOne) SetUpdatedAt(v time.Time) *PatientPrescriptionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *PatientPrescriptionUpdateOne) SetPatientID(v uuid.UUID) *PatientPrescriptionUpdateOne {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillablePatientID(v *uuid.UUID) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *PatientPrescriptionUpdateOne) SetClinicID(v uuid.UUID) *PatientPrescriptionUpdateOne {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillableClinicID(v *uuid.UUID) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetTherapistID sets the "therapist_id" field.
func (_u *PatientPrescriptionUpdateOne) SetTherapistID(v uuid.UUID) *PatientPrescriptionUpdateOne {
	_u.mutation.SetTherapistID(v)
	return _u
}

// SetNillableTherapistID sets the "therapist_id" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillableTherapistID(v *uuid.UUID) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetTherapistID(*v)
	}
	return _u
}

// SetTitle sets the "title" field.
func (_u *PatientPrescriptionUpdateOne) SetTitle(v string) *PatientPrescriptionUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillableTitle(v *string) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// ClearTitle clears the value of the "title" field.
func (_u *PatientPrescriptionUpdateOne) ClearTitle() *PatientPrescriptionUpdateOne {
	_u.mutation.ClearTitle()
	return _u
}

// SetNotes sets the "notes" field.
func (_u *PatientPrescriptionUpdateOne) SetNotes(v string) *PatientPrescriptionUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillableNotes(v *string) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// ClearNotes clears the value of the "notes" field.
func (_u *PatientPrescriptionUpdateOne) ClearNotes() *PatientPrescriptionUpdateOne {
	_u.mutation.ClearNotes()
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *PatientPrescriptionUpdateOne) SetFileKey(v string) *PatientPrescriptionUpdateOne {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillableFileKey(v *string) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// ClearFileKey clears the value of the "file_key" field.
func (_u *PatientPrescriptionUpdateOne) ClearFileKey() *PatientPrescriptionUpdateOne {
	_u.mutation.ClearFileKey()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *PatientPrescriptionUpdateOne) SetFileName(v string) *PatientPrescriptionUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillableFileName(v *string) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// ClearFileName clears the value of the "file_name" field.
func (_u *PatientPrescriptionUpdateOne) ClearFileName() *PatientPrescriptionUpdateOne {
	_u.mutation.ClearFileName()
	return _u
}

// SetPrescribedDate sets the "prescribed_date" field.
func (_u *PatientPrescriptionUpdateOne) SetPrescribedDate(v time.Time) *PatientPrescriptionUpdateOne {
	_u.mutation.SetPrescribedDate(v)
	return _u
}

// SetNillablePrescribedDate sets the "prescribed_date" field if the given value is not nil.
func (_u *PatientPrescriptionUpdateOne) SetNillablePrescribedDate(v *time.Time) *PatientPrescriptionUpdateOne {
	if v != nil {
		_u.SetPrescribedDate(*v)
	}
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *PatientPrescriptionUpdateOne) SetPatient(v *Patient) *PatientPrescriptionUpdateOne {
	return _u.SetPatientID(v.ID)
}

// SetTherapist sets the "therapist" edge to the ClinicMember entity.
func (_u *PatientPrescriptionUpdateOne) SetTherapist(v *ClinicMember) *PatientPrescriptionUpdateOne {
	return _u.SetTherapistID(v.ID)
}

// Mutation returns the PatientPrescriptionMutation object of the builder.
func (_u *PatientPrescriptionUpdateOne) Mutation() *PatientPrescriptionMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *PatientPrescriptionUpdateOne) ClearPatient() *PatientPrescriptionUpdateOne {
	_u.mutation.ClearPatient()
	return _u
}

// ClearTherapist clears the "therapist" edge to the ClinicMember entity.
func (_u *PatientPrescriptionUpdateOne) ClearTherapist() *PatientPrescriptionUpdateOne {
	_u.mutation.ClearTherapist()
	return _u
}

// Where appends a list predicates to the PatientPrescriptionUpdate builder.
func (_u *PatientPrescriptionUpdateOne) Where(ps ...predicate.PatientPrescription) *PatientPrescriptionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PatientPrescriptionUpdateOne) Select(field string, fields ...string) *PatientPrescriptionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PatientPrescription entity.
func (_u *PatientPrescriptionUpdateOne) Save(ctx context.Context) (*PatientPrescription, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatientPrescriptionUpdateOne) SaveX(ctx context.Context) *PatientPrescription {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PatientPrescriptionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatientPrescriptionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PatientPrescriptionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := patientprescription.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PatientPrescriptionUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := patientprescription.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`repo: validator failed for field "PatientPrescription.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := patientprescription.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`repo: validator failed for field "PatientPrescription.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := patientprescription.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`repo: validator failed for field "PatientPrescription.file_name": %w`, err)}
		}
	}
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientPrescription.patient"`)
	}
	if _u.mutation.TherapistCleared() && len(_u.mutation.TherapistIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientPrescription.therapist"`)
	}
	return nil
}

func (_u *PatientPrescriptionUpdateOne) sqlSave(ctx context.Context) (_node *PatientPrescription, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(patientprescription.Table, patientprescription.Columns, sqlgraph.NewFieldSpec(patientprescription.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`repo: missing "PatientPrescription.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, patientprescription.FieldID)
		for _, f := range fields {
			if !patientprescription.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("repo: invalid field %q for query", f)}
			}
			if f != patientprescription.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(patientprescription.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.ClinicID(); ok {
		_spec.SetField(patientprescription.FieldClinicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(patientprescription.FieldTitle, field.TypeString, value)
	}
	if _u.mutation.TitleCleared() {
		_spec.ClearField(patientprescription.FieldTitle, field.TypeString)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(patientprescription.FieldNotes, field.TypeString, value)
	}
	if _u.mutation.NotesCleared() {
		_spec.ClearField(patientprescription.FieldNotes, field.TypeString)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(patientprescription.FieldFileKey, field.TypeString, value)
	}
	if _u.mutation.FileKeyCleared() {
		_spec.ClearField(patientprescription.FieldFileKey, field.TypeString)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(patientprescription.FieldFileName, field.TypeString, value)
	}
	if _u.mutation.FileNameCleared() {
		_spec.ClearField(patientprescription.FieldFileName, field.TypeString)
	}
	if value, ok := _u.mutation.PrescribedDate(); ok {
		_spec.SetField(patientprescription.FieldPrescribedDate, field.TypeTime, value)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientprescription.PatientTable,
			Columns: []string{patientprescription.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientprescription.PatientTable,
			Columns: []string{patientprescription.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.TherapistCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientprescription.TherapistTable,
			Columns: []string{patientprescription.TherapistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TherapistIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientprescription.TherapistTable,
			Columns: []string{patientprescription.TherapistColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PatientPrescription{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patientprescription.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
