// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/patient"
	"github.com/Alijeyrad/simorq_backend/internal/repo/patientfile"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/Alijeyrad/simorq_backend/internal/repo/user"
	"github.com/google/uuid"
)

// PatientFileUpdate is the builder for updating PatientFile entities.
type PatientFileUpdate struct {
	config
	hooks    []Hook
	mutation *PatientFileMutation
}

// Where appends a list predicates to the PatientFileUpdate builder.
func (_u *PatientFileUpdate) Where(ps ...predicate.PatientFile) *PatientFileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPatientID sets the "patient_id" field.
func (_u *PatientFileUpdate) SetPatientID(v uuid.UUID) *PatientFileUpdate {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillablePatientID(v *uuid.UUID) *PatientFileUpdate {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *PatientFileUpdate) SetClinicID(v uuid.UUID) *PatientFileUpdate {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableClinicID(v *uuid.UUID) *PatientFileUpdate {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *PatientFileUpdate) SetUploadedBy(v uuid.UUID) *PatientFileUpdate {
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableUploadedBy(v *uuid.UUID) *PatientFileUpdate {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// SetLinkedType sets the "linked_type" field.
func (_u *PatientFileUpdate) SetLinkedType(v string) *PatientFileUpdate {
	_u.mutation.SetLinkedType(v)
	return _u
}

// SetNillableLinkedType sets the "linked_type" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableLinkedType(v *string) *PatientFileUpdate {
	if v != nil {
		_u.SetLinkedType(*v)
	}
	return _u
}

// ClearLinkedType clears the value of the "linked_type" field.
func (_u *PatientFileUpdate) ClearLinkedType() *PatientFileUpdate {
	_u.mutation.ClearLinkedType()
	return _u
}

// SetLinkedID sets the "linked_id" field.
func (_u *PatientFileUpdate) SetLinkedID(v uuid.UUID) *PatientFileUpdate {
	_u.mutation.SetLinkedID(v)
	return _u
}

// SetNillableLinkedID sets the "linked_id" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableLinkedID(v *uuid.UUID) *PatientFileUpdate {
	if v != nil {
		_u.SetLinkedID(*v)
	}
	return _u
}

// ClearLinkedID clears the value of the "linked_id" field.
func (_u *PatientFileUpdate) ClearLinkedID() *PatientFileUpdate {
	_u.mutation.ClearLinkedID()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *PatientFileUpdate) SetFileName(v string) *PatientFileUpdate {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableFileName(v *string) *PatientFileUpdate {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *PatientFileUpdate) SetFileKey(v string) *PatientFileUpdate {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableFileKey(v *string) *PatientFileUpdate {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *PatientFileUpdate) SetFileSize(v int64) *PatientFileUpdate {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableFileSize(v *int64) *PatientFileUpdate {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *PatientFileUpdate) AddFileSize(v int64) *PatientFileUpdate {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *PatientFileUpdate) ClearFileSize() *PatientFileUpdate {
	_u.mutation.ClearFileSize()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *PatientFileUpdate) SetMimeType(v string) *PatientFileUpdate {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableMimeType(v *string) *PatientFileUpdate {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *PatientFileUpdate) ClearMimeType() *PatientFileUpdate {
	_u.mutation.ClearMimeType()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PatientFileUpdate) SetDescription(v string) *PatientFileUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PatientFileUpdate) SetNillableDescription(v *string) *PatientFileUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PatientFileUpdate) ClearDescription() *PatientFileUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *PatientFileUpdate) SetPatient(v *Patient) *PatientFileUpdate {
	return _u.SetPatientID(v.ID)
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_u *PatientFileUpdate) SetUploaderID(id uuid.UUID) *PatientFileUpdate {
	_u.mutation.SetUploaderID(id)
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *PatientFileUpdate) SetUploader(v *User) *PatientFileUpdate {
	return _u.SetUploaderID(v.ID)
}

// Mutation returns the PatientFileMutation object of the builder.
func (_u *PatientFileUpdate) Mutation() *PatientFileMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *PatientFileUpdate) ClearPatient() *PatientFileUpdate {
	_u.mutation.ClearPatient()
	return _u
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *PatientFileUpdate) ClearUploader() *PatientFileUpdate {
	_u.mutation.ClearUploader()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PatientFileUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatientFileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PatientFileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatientFileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PatientFileUpdate) check() error {
	if v, ok := _u.mutation.LinkedType(); ok {
		if err := patientfile.LinkedTypeValidator(v); err != nil {
			return &ValidationError{Name: "linked_type", err: fmt.Errorf(`repo: validator failed for field "PatientFile.linked_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := patientfile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`repo: validator failed for field "PatientFile.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := patientfile.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`repo: validator failed for field "PatientFile.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := patientfile.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`repo: validator failed for field "PatientFile.mime_type": %w`, err)}
		}
	}
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientFile.patient"`)
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientFile.uploader"`)
	}
	return nil
}

func (_u *PatientFileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(patientfile.Table, patientfile.Columns, sqlgraph.NewFieldSpec(patientfile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClinicID(); ok {
		_spec.SetField(patientfile.FieldClinicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LinkedType(); ok {
		_spec.SetField(patientfile.FieldLinkedType, field.TypeString, value)
	}
	if _u.mutation.LinkedTypeCleared() {
		_spec.ClearField(patientfile.FieldLinkedType, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedID(); ok {
		_spec.SetField(patientfile.FieldLinkedID, field.TypeUUID, value)
	}
	if _u.mutation.LinkedIDCleared() {
		_spec.ClearField(patientfile.FieldLinkedID, field.TypeUUID)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(patientfile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(patientfile.FieldFileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(patientfile.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(patientfile.FieldFileSize, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(patientfile.FieldFileSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(patientfile.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(patientfile.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(patientfile.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(patientfile.FieldDescription, field.TypeString)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientfile.PatientTable,
			Columns: []string{patientfile.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientfile.PatientTable,
			Columns: []string{patientfile.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientfile.UploaderTable,
			Columns: []string{patientfile.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientfile.UploaderTable,
			Columns: []string{patientfile.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patientfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PatientFileUpdateOne is the builder for updating a single PatientFile entity.
type PatientFileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PatientFileMutation
}

// SetPatientID sets the "patient_id" field.
func (_u *PatientFileUpdateOne) SetPatientID(v uuid.UUID) *PatientFileUpdateOne {
	_u.mutation.SetPatientID(v)
	return _u
}

// SetNillablePatientID sets the "patient_id" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillablePatientID(v *uuid.UUID) *PatientFileUpdateOne {
	if v != nil {
		_u.SetPatientID(*v)
	}
	return _u
}

// SetClinicID sets the "clinic_id" field.
func (_u *PatientFileUpdateOne) SetClinicID(v uuid.UUID) *PatientFileUpdateOne {
	_u.mutation.SetClinicID(v)
	return _u
}

// SetNillableClinicID sets the "clinic_id" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableClinicID(v *uuid.UUID) *PatientFileUpdateOne {
	if v != nil {
		_u.SetClinicID(*v)
	}
	return _u
}

// SetUploadedBy sets the "uploaded_by" field.
func (_u *PatientFileUpdateOne) SetUploadedBy(v uuid.UUID) *PatientFileUpdateOne {
	_u.mutation.SetUploadedBy(v)
	return _u
}

// SetNillableUploadedBy sets the "uploaded_by" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableUploadedBy(v *uuid.UUID) *PatientFileUpdateOne {
	if v != nil {
		_u.SetUploadedBy(*v)
	}
	return _u
}

// SetLinkedType sets the "linked_type" field.
func (_u *PatientFileUpdateOne) SetLinkedType(v string) *PatientFileUpdateOne {
	_u.mutation.SetLinkedType(v)
	return _u
}

// SetNillableLinkedType sets the "linked_type" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableLinkedType(v *string) *PatientFileUpdateOne {
	if v != nil {
		_u.SetLinkedType(*v)
	}
	return _u
}

// ClearLinkedType clears the value of the "linked_type" field.
func (_u *PatientFileUpdateOne) ClearLinkedType() *PatientFileUpdateOne {
	_u.mutation.ClearLinkedType()
	return _u
}

// SetLinkedID sets the "linked_id" field.
func (_u *PatientFileUpdateOne) SetLinkedID(v uuid.UUID) *PatientFileUpdateOne {
	_u.mutation.SetLinkedID(v)
	return _u
}

// SetNillableLinkedID sets the "linked_id" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableLinkedID(v *uuid.UUID) *PatientFileUpdateOne {
	if v != nil {
		_u.SetLinkedID(*v)
	}
	return _u
}

// ClearLinkedID clears the value of the "linked_id" field.
func (_u *PatientFileUpdateOne) ClearLinkedID() *PatientFileUpdateOne {
	_u.mutation.ClearLinkedID()
	return _u
}

// SetFileName sets the "file_name" field.
func (_u *PatientFileUpdateOne) SetFileName(v string) *PatientFileUpdateOne {
	_u.mutation.SetFileName(v)
	return _u
}

// SetNillableFileName sets the "file_name" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableFileName(v *string) *PatientFileUpdateOne {
	if v != nil {
		_u.SetFileName(*v)
	}
	return _u
}

// SetFileKey sets the "file_key" field.
func (_u *PatientFileUpdateOne) SetFileKey(v string) *PatientFileUpdateOne {
	_u.mutation.SetFileKey(v)
	return _u
}

// SetNillableFileKey sets the "file_key" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableFileKey(v *string) *PatientFileUpdateOne {
	if v != nil {
		_u.SetFileKey(*v)
	}
	return _u
}

// SetFileSize sets the "file_size" field.
func (_u *PatientFileUpdateOne) SetFileSize(v int64) *PatientFileUpdateOne {
	_u.mutation.ResetFileSize()
	_u.mutation.SetFileSize(v)
	return _u
}

// SetNillableFileSize sets the "file_size" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableFileSize(v *int64) *PatientFileUpdateOne {
	if v != nil {
		_u.SetFileSize(*v)
	}
	return _u
}

// AddFileSize adds value to the "file_size" field.
func (_u *PatientFileUpdateOne) AddFileSize(v int64) *PatientFileUpdateOne {
	_u.mutation.AddFileSize(v)
	return _u
}

// ClearFileSize clears the value of the "file_size" field.
func (_u *PatientFileUpdateOne) ClearFileSize() *PatientFileUpdateOne {
	_u.mutation.ClearFileSize()
	return _u
}

// SetMimeType sets the "mime_type" field.
func (_u *PatientFileUpdateOne) SetMimeType(v string) *PatientFileUpdateOne {
	_u.mutation.SetMimeType(v)
	return _u
}

// SetNillableMimeType sets the "mime_type" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableMimeType(v *string) *PatientFileUpdateOne {
	if v != nil {
		_u.SetMimeType(*v)
	}
	return _u
}

// ClearMimeType clears the value of the "mime_type" field.
func (_u *PatientFileUpdateOne) ClearMimeType() *PatientFileUpdateOne {
	_u.mutation.ClearMimeType()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PatientFileUpdateOne) SetDescription(v string) *PatientFileUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PatientFileUpdateOne) SetNillableDescription(v *string) *PatientFileUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PatientFileUpdateOne) ClearDescription() *PatientFileUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_u *PatientFileUpdateOne) SetPatient(v *Patient) *PatientFileUpdateOne {
	return _u.SetPatientID(v.ID)
}

// SetUploaderID sets the "uploader" edge to the User entity by ID.
func (_u *PatientFileUpdateOne) SetUploaderID(id uuid.UUID) *PatientFileUpdateOne {
	_u.mutation.SetUploaderID(id)
	return _u
}

// SetUploader sets the "uploader" edge to the User entity.
func (_u *PatientFileUpdateOne) SetUploader(v *User) *PatientFileUpdateOne {
	return _u.SetUploaderID(v.ID)
}

// Mutation returns the PatientFileMutation object of the builder.
func (_u *PatientFileUpdateOne) Mutation() *PatientFileMutation {
	return _u.mutation
}

// ClearPatient clears the "patient" edge to the Patient entity.
func (_u *PatientFileUpdateOne) ClearPatient() *PatientFileUpdateOne {
	_u.mutation.ClearPatient()
	return _u
}

// ClearUploader clears the "uploader" edge to the User entity.
func (_u *PatientFileUpdateOne) ClearUploader() *PatientFileUpdateOne {
	_u.mutation.ClearUploader()
	return _u
}

// Where appends a list predicates to the PatientFileUpdate builder.
func (_u *PatientFileUpdateOne) Where(ps ...predicate.PatientFile) *PatientFileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PatientFileUpdateOne) Select(field string, fields ...string) *PatientFileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PatientFile entity.
func (_u *PatientFileUpdateOne) Save(ctx context.Context) (*PatientFile, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PatientFileUpdateOne) SaveX(ctx context.Context) *PatientFile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PatientFileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PatientFileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PatientFileUpdateOne) check() error {
	if v, ok := _u.mutation.LinkedType(); ok {
		if err := patientfile.LinkedTypeValidator(v); err != nil {
			return &ValidationError{Name: "linked_type", err: fmt.Errorf(`repo: validator failed for field "PatientFile.linked_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileName(); ok {
		if err := patientfile.FileNameValidator(v); err != nil {
			return &ValidationError{Name: "file_name", err: fmt.Errorf(`repo: validator failed for field "PatientFile.file_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.FileKey(); ok {
		if err := patientfile.FileKeyValidator(v); err != nil {
			return &ValidationError{Name: "file_key", err: fmt.Errorf(`repo: validator failed for field "PatientFile.file_key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.MimeType(); ok {
		if err := patientfile.MimeTypeValidator(v); err != nil {
			return &ValidationError{Name: "mime_type", err: fmt.Errorf(`repo: validator failed for field "PatientFile.mime_type": %w`, err)}
		}
	}
	if _u.mutation.PatientCleared() && len(_u.mutation.PatientIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientFile.patient"`)
	}
	if _u.mutation.UploaderCleared() && len(_u.mutation.UploaderIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "PatientFile.uploader"`)
	}
	return nil
}

func (_u *PatientFileUpdateOne) sqlSave(ctx context.Context) (_node *PatientFile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(patientfile.Table, patientfile.Columns, sqlgraph.NewFieldSpec(patientfile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`repo: missing "PatientFile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, patientfile.FieldID)
		for _, f := range fields {
			if !patientfile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("repo: invalid field %q for query", f)}
			}
			if f != patientfile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClinicID(); ok {
		_spec.SetField(patientfile.FieldClinicID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.LinkedType(); ok {
		_spec.SetField(patientfile.FieldLinkedType, field.TypeString, value)
	}
	if _u.mutation.LinkedTypeCleared() {
		_spec.ClearField(patientfile.FieldLinkedType, field.TypeString)
	}
	if value, ok := _u.mutation.LinkedID(); ok {
		_spec.SetField(patientfile.FieldLinkedID, field.TypeUUID, value)
	}
	if _u.mutation.LinkedIDCleared() {
		_spec.ClearField(patientfile.FieldLinkedID, field.TypeUUID)
	}
	if value, ok := _u.mutation.FileName(); ok {
		_spec.SetField(patientfile.FieldFileName, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileKey(); ok {
		_spec.SetField(patientfile.FieldFileKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FileSize(); ok {
		_spec.SetField(patientfile.FieldFileSize, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedFileSize(); ok {
		_spec.AddField(patientfile.FieldFileSize, field.TypeInt64, value)
	}
	if _u.mutation.FileSizeCleared() {
		_spec.ClearField(patientfile.FieldFileSize, field.TypeInt64)
	}
	if value, ok := _u.mutation.MimeType(); ok {
		_spec.SetField(patientfile.FieldMimeType, field.TypeString, value)
	}
	if _u.mutation.MimeTypeCleared() {
		_spec.ClearField(patientfile.FieldMimeType, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(patientfile.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(patientfile.FieldDescription, field.TypeString)
	}
	if _u.mutation.PatientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientfile.PatientTable,
			Columns: []string{patientfile.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patientfile.PatientTable,
			Columns: []string{patientfile.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UploaderCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientfile.UploaderTable,
			Columns: []string{patientfile.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UploaderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patientfile.UploaderTable,
			Columns: []string{patientfile.UploaderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PatientFile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{patientfile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
