// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/clinicmember"
	"github.com/Alijeyrad/simorq_backend/internal/repo/patient"
	"github.com/Alijeyrad/simorq_backend/internal/repo/patienttest"
	"github.com/Alijeyrad/simorq_backend/internal/repo/psychtest"
	"github.com/google/uuid"
)

// PatientTestCreate is the builder for creating a PatientTest entity.
type PatientTestCreate struct {
	config
	mutation *PatientTestMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *PatientTestCreate) SetCreatedAt(v time.Time) *PatientTestCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableCreatedAt(v *time.Time) *PatientTestCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *PatientTestCreate) SetUpdatedAt(v time.Time) *PatientTestCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableUpdatedAt(v *time.Time) *PatientTestCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetPatientID sets the "patient_id" field.
func (_c *PatientTestCreate) SetPatientID(v uuid.UUID) *PatientTestCreate {
	_c.mutation.SetPatientID(v)
	return _c
}

// SetClinicID sets the "clinic_id" field.
func (_c *PatientTestCreate) SetClinicID(v uuid.UUID) *PatientTestCreate {
	_c.mutation.SetClinicID(v)
	return _c
}

// SetTestID sets the "test_id" field.
func (_c *PatientTestCreate) SetTestID(v uuid.UUID) *PatientTestCreate {
	_c.mutation.SetTestID(v)
	return _c
}

// SetNillableTestID sets the "test_id" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableTestID(v *uuid.UUID) *PatientTestCreate {
	if v != nil {
		_c.SetTestID(*v)
	}
	return _c
}

// SetAdministeredBy sets the "administered_by" field.
func (_c *PatientTestCreate) SetAdministeredBy(v uuid.UUID) *PatientTestCreate {
	_c.mutation.SetAdministeredBy(v)
	return _c
}

// SetNillableAdministeredBy sets the "administered_by" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableAdministeredBy(v *uuid.UUID) *PatientTestCreate {
	if v != nil {
		_c.SetAdministeredBy(*v)
	}
	return _c
}

// SetTestName sets the "test_name" field.
func (_c *PatientTestCreate) SetTestName(v string) *PatientTestCreate {
	_c.mutation.SetTestName(v)
	return _c
}

// SetNillableTestName sets the "test_name" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableTestName(v *string) *PatientTestCreate {
	if v != nil {
		_c.SetTestName(*v)
	}
	return _c
}

// SetRawScores sets the "raw_scores" field.
func (_c *PatientTestCreate) SetRawScores(v map[string]interface{}) *PatientTestCreate {
	_c.mutation.SetRawScores(v)
	return _c
}

// SetComputedScores sets the "computed_scores" field.
func (_c *PatientTestCreate) SetComputedScores(v map[string]interface{}) *PatientTestCreate {
	_c.mutation.SetComputedScores(v)
	return _c
}

// SetInterpretation sets the "interpretation" field.
func (_c *PatientTestCreate) SetInterpretation(v string) *PatientTestCreate {
	_c.mutation.SetInterpretation(v)
	return _c
}

// SetNillableInterpretation sets the "interpretation" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableInterpretation(v *string) *PatientTestCreate {
	if v != nil {
		_c.SetInterpretation(*v)
	}
	return _c
}

// SetTestDate sets the "test_date" field.
func (_c *PatientTestCreate) SetTestDate(v time.Time) *PatientTestCreate {
	_c.mutation.SetTestDate(v)
	return _c
}

// SetNillableTestDate sets the "test_date" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableTestDate(v *time.Time) *PatientTestCreate {
	if v != nil {
		_c.SetTestDate(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *PatientTestCreate) SetStatus(v patienttest.Status) *PatientTestCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableStatus(v *patienttest.Status) *PatientTestCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PatientTestCreate) SetID(v uuid.UUID) *PatientTestCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PatientTestCreate) SetNillableID(v *uuid.UUID) *PatientTestCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPatient sets the "patient" edge to the Patient entity.
func (_c *PatientTestCreate) SetPatient(v *Patient) *PatientTestCreate {
	return _c.SetPatientID(v.ID)
}

// SetPsychTestID sets the "psych_test" edge to the PsychTest entity by ID.
func (_c *PatientTestCreate) SetPsychTestID(id uuid.UUID) *PatientTestCreate {
	_c.mutation.SetPsychTestID(id)
	return _c
}

// SetNillablePsychTestID sets the "psych_test" edge to the PsychTest entity by ID if the given value is not nil.
func (_c *PatientTestCreate) SetNillablePsychTestID(id *uuid.UUID) *PatientTestCreate {
	if id != nil {
		_c = _c.SetPsychTestID(*id)
	}
	return _c
}

// SetPsychTest sets the "psych_test" edge to the PsychTest entity.
func (_c *PatientTestCreate) SetPsychTest(v *PsychTest) *PatientTestCreate {
	return _c.SetPsychTestID(v.ID)
}

// SetAdministratorID sets the "administrator" edge to the ClinicMember entity by ID.
func (_c *PatientTestCreate) SetAdministratorID(id uuid.UUID) *PatientTestCreate {
	_c.mutation.SetAdministratorID(id)
	return _c
}

// SetNillableAdministratorID sets the "administrator" edge to the ClinicMember entity by ID if the given value is not nil.
func (_c *PatientTestCreate) SetNillableAdministratorID(id *uuid.UUID) *PatientTestCreate {
	if id != nil {
		_c = _c.SetAdministratorID(*id)
	}
	return _c
}

// SetAdministrator sets the "administrator" edge to the ClinicMember entity.
func (_c *PatientTestCreate) SetAdministrator(v *ClinicMember) *PatientTestCreate {
	return _c.SetAdministratorID(v.ID)
}

// Mutation returns the PatientTestMutation object of the builder.
func (_c *PatientTestCreate) Mutation() *PatientTestMutation {
	return _c.mutation
}

// Save creates the PatientTest in the database.
func (_c *PatientTestCreate) Save(ctx context.Context) (*PatientTest, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PatientTestCreate) SaveX(ctx context.Context) *PatientTest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientTestCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientTestCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PatientTestCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := patienttest.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := patienttest.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.TestDate(); !ok {
		v := patienttest.DefaultTestDate()
		_c.mutation.SetTestDate(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := patienttest.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := patienttest.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PatientTestCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`repo: missing required field "PatientTest.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`repo: missing required field "PatientTest.updated_at"`)}
	}
	if _, ok := _c.mutation.PatientID(); !ok {
		return &ValidationError{Name: "patient_id", err: errors.New(`repo: missing required field "PatientTest.patient_id"`)}
	}
	if _, ok := _c.mutation.ClinicID(); !ok {
		return &ValidationError{Name: "clinic_id", err: errors.New(`repo: missing required field "PatientTest.clinic_id"`)}
	}
	if v, ok := _c.mutation.TestName(); ok {
		if err := patienttest.TestNameValidator(v); err != nil {
			return &ValidationError{Name: "test_name", err: fmt.Errorf(`repo: validator failed for field "PatientTest.test_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.TestDate(); !ok {
		return &ValidationError{Name: "test_date", err: errors.New(`repo: missing required field "PatientTest.test_date"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`repo: missing required field "PatientTest.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := patienttest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`repo: validator failed for field "PatientTest.status": %w`, err)}
		}
	}
	if len(_c.mutation.PatientIDs()) == 0 {
		return &ValidationError{Name: "patient", err: errors.New(`repo: missing required edge "PatientTest.patient"`)}
	}
	return nil
}

func (_c *PatientTestCreate) sqlSave(ctx context.Context) (*PatientTest, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PatientTestCreate) createSpec() (*PatientTest, *sqlgraph.CreateSpec) {
	var (
		_node = &PatientTest{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(patienttest.Table, sqlgraph.NewFieldSpec(patienttest.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(patienttest.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(patienttest.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.ClinicID(); ok {
		_spec.SetField(patienttest.FieldClinicID, field.TypeUUID, value)
		_node.ClinicID = value
	}
	if value, ok := _c.mutation.TestName(); ok {
		_spec.SetField(patienttest.FieldTestName, field.TypeString, value)
		_node.TestName = &value
	}
	if value, ok := _c.mutation.RawScores(); ok {
		_spec.SetField(patienttest.FieldRawScores, field.TypeJSON, value)
		_node.RawScores = value
	}
	if value, ok := _c.mutation.ComputedScores(); ok {
		_spec.SetField(patienttest.FieldComputedScores, field.TypeJSON, value)
		_node.ComputedScores = value
	}
	if value, ok := _c.mutation.Interpretation(); ok {
		_spec.SetField(patienttest.FieldInterpretation, field.TypeString, value)
		_node.Interpretation = &value
	}
	if value, ok := _c.mutation.TestDate(); ok {
		_spec.SetField(patienttest.FieldTestDate, field.TypeTime, value)
		_node.TestDate = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(patienttest.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if nodes := _c.mutation.PatientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   patienttest.PatientTable,
			Columns: []string{patienttest.PatientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(patient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PatientID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PsychTestIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patienttest.PsychTestTable,
			Columns: []string{patienttest.PsychTestColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(psychtest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TestID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AdministratorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   patienttest.AdministratorTable,
			Columns: []string{patienttest.AdministratorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.AdministeredBy = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PatientTestCreateBulk is the builder for creating many PatientTest entities in bulk.
type PatientTestCreateBulk struct {
	config
	err      error
	builders []*PatientTestCreate
}

// Save creates the PatientTest entities in the database.
func (_c *PatientTestCreateBulk) Save(ctx context.Context) ([]*PatientTest, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PatientTest, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PatientTestMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PatientTestCreateBulk) SaveX(ctx context.Context) []*PatientTest {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PatientTestCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PatientTestCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
