// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/clinicmember"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/Alijeyrad/simorq_backend/internal/repo/therapistprofile"
	"github.com/google/uuid"
)

// TherapistProfileUpdate is the builder for updating TherapistProfile entities.
type TherapistProfileUpdate struct {
	config
	hooks    []Hook
	mutation *TherapistProfileMutation
}

// Where appends a list predicates to the TherapistProfileUpdate builder.
func (_u *TherapistProfileUpdate) Where(ps ...predicate.TherapistProfile) *TherapistProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TherapistProfileUpdate) SetUpdatedAt(v time.Time) *TherapistProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClinicMemberID sets the "clinic_member_id" field.
func (_u *TherapistProfileUpdate) SetClinicMemberID(v uuid.UUID) *TherapistProfileUpdate {
	_u.mutation.SetClinicMemberID(v)
	return _u
}

// SetNillableClinicMemberID sets the "clinic_member_id" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableClinicMemberID(v *uuid.UUID) *TherapistProfileUpdate {
	if v != nil {
		_u.SetClinicMemberID(*v)
	}
	return _u
}

// SetEducation sets the "education" field.
func (_u *TherapistProfileUpdate) SetEducation(v string) *TherapistProfileUpdate {
	_u.mutation.SetEducation(v)
	return _u
}

// SetNillableEducation sets the "education" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableEducation(v *string) *TherapistProfileUpdate {
	if v != nil {
		_u.SetEducation(*v)
	}
	return _u
}

// ClearEducation clears the value of the "education" field.
func (_u *TherapistProfileUpdate) ClearEducation() *TherapistProfileUpdate {
	_u.mutation.ClearEducation()
	return _u
}

// SetPsychologyLicense sets the "psychology_license" field.
func (_u *TherapistProfileUpdate) SetPsychologyLicense(v string) *TherapistProfileUpdate {
	_u.mutation.SetPsychologyLicense(v)
	return _u
}

// SetNillablePsychologyLicense sets the "psychology_license" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillablePsychologyLicense(v *string) *TherapistProfileUpdate {
	if v != nil {
		_u.SetPsychologyLicense(*v)
	}
	return _u
}

// ClearPsychologyLicense clears the value of the "psychology_license" field.
func (_u *TherapistProfileUpdate) ClearPsychologyLicense() *TherapistProfileUpdate {
	_u.mutation.ClearPsychologyLicense()
	return _u
}

// SetApproach sets the "approach" field.
func (_u *TherapistProfileUpdate) SetApproach(v string) *TherapistProfileUpdate {
	_u.mutation.SetApproach(v)
	return _u
}

// SetNillableApproach sets the "approach" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableApproach(v *string) *TherapistProfileUpdate {
	if v != nil {
		_u.SetApproach(*v)
	}
	return _u
}

// ClearApproach clears the value of the "approach" field.
func (_u *TherapistProfileUpdate) ClearApproach() *TherapistProfileUpdate {
	_u.mutation.ClearApproach()
	return _u
}

// SetSpecialties sets the "specialties" field.
func (_u *TherapistProfileUpdate) SetSpecialties(v []string) *TherapistProfileUpdate {
	_u.mutation.SetSpecialties(v)
	return _u
}

// AppendSpecialties appends value to the "specialties" field.
func (_u *TherapistProfileUpdate) AppendSpecialties(v []string) *TherapistProfileUpdate {
	_u.mutation.AppendSpecialties(v)
	return _u
}

// ClearSpecialties clears the value of the "specialties" field.
func (_u *TherapistProfileUpdate) ClearSpecialties() *TherapistProfileUpdate {
	_u.mutation.ClearSpecialties()
	return _u
}

// SetBio sets the "bio" field.
func (_u *TherapistProfileUpdate) SetBio(v string) *TherapistProfileUpdate {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableBio(v *string) *TherapistProfileUpdate {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// ClearBio clears the value of the "bio" field.
func (_u *TherapistProfileUpdate) ClearBio() *TherapistProfileUpdate {
	_u.mutation.ClearBio()
	return _u
}

// SetRating sets the "rating" field.
func (_u *TherapistProfileUpdate) SetRating(v float64) *TherapistProfileUpdate {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableRating(v *float64) *TherapistProfileUpdate {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *TherapistProfileUpdate) AddRating(v float64) *TherapistProfileUpdate {
	_u.mutation.AddRating(v)
	return _u
}

// SetSessionPrice sets the "session_price" field.
func (_u *TherapistProfileUpdate) SetSessionPrice(v int64) *TherapistProfileUpdate {
	_u.mutation.ResetSessionPrice()
	_u.mutation.SetSessionPrice(v)
	return _u
}

// SetNillableSessionPrice sets the "session_price" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableSessionPrice(v *int64) *TherapistProfileUpdate {
	if v != nil {
		_u.SetSessionPrice(*v)
	}
	return _u
}

// AddSessionPrice adds value to the "session_price" field.
func (_u *TherapistProfileUpdate) AddSessionPrice(v int64) *TherapistProfileUpdate {
	_u.mutation.AddSessionPrice(v)
	return _u
}

// ClearSessionPrice clears the value of the "session_price" field.
func (_u *TherapistProfileUpdate) ClearSessionPrice() *TherapistProfileUpdate {
	_u.mutation.ClearSessionPrice()
	return _u
}

// SetSessionDurationMin sets the "session_duration_min" field.
func (_u *TherapistProfileUpdate) SetSessionDurationMin(v int) *TherapistProfileUpdate {
	_u.mutation.ResetSessionDurationMin()
	_u.mutation.SetSessionDurationMin(v)
	return _u
}

// SetNillableSessionDurationMin sets the "session_duration_min" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableSessionDurationMin(v *int) *TherapistProfileUpdate {
	if v != nil {
		_u.SetSessionDurationMin(*v)
	}
	return _u
}

// AddSessionDurationMin adds value to the "session_duration_min" field.
func (_u *TherapistProfileUpdate) AddSessionDurationMin(v int) *TherapistProfileUpdate {
	_u.mutation.AddSessionDurationMin(v)
	return _u
}

// ClearSessionDurationMin clears the value of the "session_duration_min" field.
func (_u *TherapistProfileUpdate) ClearSessionDurationMin() *TherapistProfileUpdate {
	_u.mutation.ClearSessionDurationMin()
	return _u
}

// SetIsAccepting sets the "is_accepting" field.
func (_u *TherapistProfileUpdate) SetIsAccepting(v bool) *TherapistProfileUpdate {
	_u.mutation.SetIsAccepting(v)
	return _u
}

// SetNillableIsAccepting sets the "is_accepting" field if the given value is not nil.
func (_u *TherapistProfileUpdate) SetNillableIsAccepting(v *bool) *TherapistProfileUpdate {
	if v != nil {
		_u.SetIsAccepting(*v)
	}
	return _u
}

// SetMemberID sets the "member" edge to the ClinicMember entity by ID.
func (_u *TherapistProfileUpdate) SetMemberID(id uuid.UUID) *TherapistProfileUpdate {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the ClinicMember entity.
func (_u *TherapistProfileUpdate) SetMember(v *ClinicMember) *TherapistProfileUpdate {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the TherapistProfileMutation object of the builder.
func (_u *TherapistProfileUpdate) Mutation() *TherapistProfileMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the ClinicMember entity.
func (_u *TherapistProfileUpdate) ClearMember() *TherapistProfileUpdate {
	_u.mutation.ClearMember()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TherapistProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TherapistProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TherapistProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TherapistProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TherapistProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := therapistprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TherapistProfileUpdate) check() error {
	if v, ok := _u.mutation.Education(); ok {
		if err := therapistprofile.EducationValidator(v); err != nil {
			return &ValidationError{Name: "education", err: fmt.Errorf(`repo: validator failed for field "TherapistProfile.education": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PsychologyLicense(); ok {
		if err := therapistprofile.PsychologyLicenseValidator(v); err != nil {
			return &ValidationError{Name: "psychology_license", err: fmt.Errorf(`repo: validator failed for field "TherapistProfile.psychology_license": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Approach(); ok {
		if err := therapistprofile.ApproachValidator(v); err != nil {
			return &ValidationError{Name: "approach", err: fmt.Errorf(`repo: validator failed for field "TherapistProfile.approach": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "TherapistProfile.member"`)
	}
	return nil
}

func (_u *TherapistProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(therapistprofile.Table, therapistprofile.Columns, sqlgraph.NewFieldSpec(therapistprofile.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(therapistprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Education(); ok {
		_spec.SetField(therapistprofile.FieldEducation, field.TypeString, value)
	}
	if _u.mutation.EducationCleared() {
		_spec.ClearField(therapistprofile.FieldEducation, field.TypeString)
	}
	if value, ok := _u.mutation.PsychologyLicense(); ok {
		_spec.SetField(therapistprofile.FieldPsychologyLicense, field.TypeString, value)
	}
	if _u.mutation.PsychologyLicenseCleared() {
		_spec.ClearField(therapistprofile.FieldPsychologyLicense, field.TypeString)
	}
	if value, ok := _u.mutation.Approach(); ok {
		_spec.SetField(therapistprofile.FieldApproach, field.TypeString, value)
	}
	if _u.mutation.ApproachCleared() {
		_spec.ClearField(therapistprofile.FieldApproach, field.TypeString)
	}
	if value, ok := _u.mutation.Specialties(); ok {
		_spec.SetField(therapistprofile.FieldSpecialties, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecialties(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, therapistprofile.FieldSpecialties, value)
		})
	}
	if _u.mutation.SpecialtiesCleared() {
		_spec.ClearField(therapistprofile.FieldSpecialties, field.TypeJSON)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(therapistprofile.FieldBio, field.TypeString, value)
	}
	if _u.mutation.BioCleared() {
		_spec.ClearField(therapistprofile.FieldBio, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(therapistprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(therapistprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SessionPrice(); ok {
		_spec.SetField(therapistprofile.FieldSessionPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionPrice(); ok {
		_spec.AddField(therapistprofile.FieldSessionPrice, field.TypeInt64, value)
	}
	if _u.mutation.SessionPriceCleared() {
		_spec.ClearField(therapistprofile.FieldSessionPrice, field.TypeInt64)
	}
	if value, ok := _u.mutation.SessionDurationMin(); ok {
		_spec.SetField(therapistprofile.FieldSessionDurationMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionDurationMin(); ok {
		_spec.AddField(therapistprofile.FieldSessionDurationMin, field.TypeInt, value)
	}
	if _u.mutation.SessionDurationMinCleared() {
		_spec.ClearField(therapistprofile.FieldSessionDurationMin, field.TypeInt)
	}
	if value, ok := _u.mutation.IsAccepting(); ok {
		_spec.SetField(therapistprofile.FieldIsAccepting, field.TypeBool, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   therapistprofile.MemberTable,
			Columns: []string{therapistprofile.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   therapistprofile.MemberTable,
			Columns: []string{therapistprofile.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{therapistprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TherapistProfileUpdateOne is the builder for updating a single TherapistProfile entity.
type TherapistProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TherapistProfileMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *TherapistProfileUpdateOne) SetUpdatedAt(v time.Time) *TherapistProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetClinicMemberID sets the "clinic_member_id" field.
func (_u *TherapistProfileUpdateOne) SetClinicMemberID(v uuid.UUID) *TherapistProfileUpdateOne {
	_u.mutation.SetClinicMemberID(v)
	return _u
}

// SetNillableClinicMemberID sets the "clinic_member_id" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableClinicMemberID(v *uuid.UUID) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetClinicMemberID(*v)
	}
	return _u
}

// SetEducation sets the "education" field.
func (_u *TherapistProfileUpdateOne) SetEducation(v string) *TherapistProfileUpdateOne {
	_u.mutation.SetEducation(v)
	return _u
}

// SetNillableEducation sets the "education" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableEducation(v *string) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetEducation(*v)
	}
	return _u
}

// ClearEducation clears the value of the "education" field.
func (_u *TherapistProfileUpdateOne) ClearEducation() *TherapistProfileUpdateOne {
	_u.mutation.ClearEducation()
	return _u
}

// SetPsychologyLicense sets the "psychology_license" field.
func (_u *TherapistProfileUpdateOne) SetPsychologyLicense(v string) *TherapistProfileUpdateOne {
	_u.mutation.SetPsychologyLicense(v)
	return _u
}

// SetNillablePsychologyLicense sets the "psychology_license" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillablePsychologyLicense(v *string) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetPsychologyLicense(*v)
	}
	return _u
}

// ClearPsychologyLicense clears the value of the "psychology_license" field.
func (_u *TherapistProfileUpdateOne) ClearPsychologyLicense() *TherapistProfileUpdateOne {
	_u.mutation.ClearPsychologyLicense()
	return _u
}

// SetApproach sets the "approach" field.
func (_u *TherapistProfileUpdateOne) SetApproach(v string) *TherapistProfileUpdateOne {
	_u.mutation.SetApproach(v)
	return _u
}

// SetNillableApproach sets the "approach" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableApproach(v *string) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetApproach(*v)
	}
	return _u
}

// ClearApproach clears the value of the "approach" field.
func (_u *TherapistProfileUpdateOne) ClearApproach() *TherapistProfileUpdateOne {
	_u.mutation.ClearApproach()
	return _u
}

// SetSpecialties sets the "specialties" field.
func (_u *TherapistProfileUpdateOne) SetSpecialties(v []string) *TherapistProfileUpdateOne {
	_u.mutation.SetSpecialties(v)
	return _u
}

// AppendSpecialties appends value to the "specialties" field.
func (_u *TherapistProfileUpdateOne) AppendSpecialties(v []string) *TherapistProfileUpdateOne {
	_u.mutation.AppendSpecialties(v)
	return _u
}

// ClearSpecialties clears the value of the "specialties" field.
func (_u *TherapistProfileUpdateOne) ClearSpecialties() *TherapistProfileUpdateOne {
	_u.mutation.ClearSpecialties()
	return _u
}

// SetBio sets the "bio" field.
func (_u *TherapistProfileUpdateOne) SetBio(v string) *TherapistProfileUpdateOne {
	_u.mutation.SetBio(v)
	return _u
}

// SetNillableBio sets the "bio" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableBio(v *string) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetBio(*v)
	}
	return _u
}

// ClearBio clears the value of the "bio" field.
func (_u *TherapistProfileUpdateOne) ClearBio() *TherapistProfileUpdateOne {
	_u.mutation.ClearBio()
	return _u
}

// SetRating sets the "rating" field.
func (_u *TherapistProfileUpdateOne) SetRating(v float64) *TherapistProfileUpdateOne {
	_u.mutation.ResetRating()
	_u.mutation.SetRating(v)
	return _u
}

// SetNillableRating sets the "rating" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableRating(v *float64) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetRating(*v)
	}
	return _u
}

// AddRating adds value to the "rating" field.
func (_u *TherapistProfileUpdateOne) AddRating(v float64) *TherapistProfileUpdateOne {
	_u.mutation.AddRating(v)
	return _u
}

// SetSessionPrice sets the "session_price" field.
func (_u *TherapistProfileUpdateOne) SetSessionPrice(v int64) *TherapistProfileUpdateOne {
	_u.mutation.ResetSessionPrice()
	_u.mutation.SetSessionPrice(v)
	return _u
}

// SetNillableSessionPrice sets the "session_price" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableSessionPrice(v *int64) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetSessionPrice(*v)
	}
	return _u
}

// AddSessionPrice adds value to the "session_price" field.
func (_u *TherapistProfileUpdateOne) AddSessionPrice(v int64) *TherapistProfileUpdateOne {
	_u.mutation.AddSessionPrice(v)
	return _u
}

// ClearSessionPrice clears the value of the "session_price" field.
func (_u *TherapistProfileUpdateOne) ClearSessionPrice() *TherapistProfileUpdateOne {
	_u.mutation.ClearSessionPrice()
	return _u
}

// SetSessionDurationMin sets the "session_duration_min" field.
func (_u *TherapistProfileUpdateOne) SetSessionDurationMin(v int) *TherapistProfileUpdateOne {
	_u.mutation.ResetSessionDurationMin()
	_u.mutation.SetSessionDurationMin(v)
	return _u
}

// SetNillableSessionDurationMin sets the "session_duration_min" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableSessionDurationMin(v *int) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetSessionDurationMin(*v)
	}
	return _u
}

// AddSessionDurationMin adds value to the "session_duration_min" field.
func (_u *TherapistProfileUpdateOne) AddSessionDurationMin(v int) *TherapistProfileUpdateOne {
	_u.mutation.AddSessionDurationMin(v)
	return _u
}

// ClearSessionDurationMin clears the value of the "session_duration_min" field.
func (_u *TherapistProfileUpdateOne) ClearSessionDurationMin() *TherapistProfileUpdateOne {
	_u.mutation.ClearSessionDurationMin()
	return _u
}

// SetIsAccepting sets the "is_accepting" field.
func (_u *TherapistProfileUpdateOne) SetIsAccepting(v bool) *TherapistProfileUpdateOne {
	_u.mutation.SetIsAccepting(v)
	return _u
}

// SetNillableIsAccepting sets the "is_accepting" field if the given value is not nil.
func (_u *TherapistProfileUpdateOne) SetNillableIsAccepting(v *bool) *TherapistProfileUpdateOne {
	if v != nil {
		_u.SetIsAccepting(*v)
	}
	return _u
}

// SetMemberID sets the "member" edge to the ClinicMember entity by ID.
func (_u *TherapistProfileUpdateOne) SetMemberID(id uuid.UUID) *TherapistProfileUpdateOne {
	_u.mutation.SetMemberID(id)
	return _u
}

// SetMember sets the "member" edge to the ClinicMember entity.
func (_u *TherapistProfileUpdateOne) SetMember(v *ClinicMember) *TherapistProfileUpdateOne {
	return _u.SetMemberID(v.ID)
}

// Mutation returns the TherapistProfileMutation object of the builder.
func (_u *TherapistProfileUpdateOne) Mutation() *TherapistProfileMutation {
	return _u.mutation
}

// ClearMember clears the "member" edge to the ClinicMember entity.
func (_u *TherapistProfileUpdateOne) ClearMember() *TherapistProfileUpdateOne {
	_u.mutation.ClearMember()
	return _u
}

// Where appends a list predicates to the TherapistProfileUpdate builder.
func (_u *TherapistProfileUpdateOne) Where(ps ...predicate.TherapistProfile) *TherapistProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TherapistProfileUpdateOne) Select(field string, fields ...string) *TherapistProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TherapistProfile entity.
func (_u *TherapistProfileUpdateOne) Save(ctx context.Context) (*TherapistProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TherapistProfileUpdateOne) SaveX(ctx context.Context) *TherapistProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TherapistProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TherapistProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *TherapistProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := therapistprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TherapistProfileUpdateOne) check() error {
	if v, ok := _u.mutation.Education(); ok {
		if err := therapistprofile.EducationValidator(v); err != nil {
			return &ValidationError{Name: "education", err: fmt.Errorf(`repo: validator failed for field "TherapistProfile.education": %w`, err)}
		}
	}
	if v, ok := _u.mutation.PsychologyLicense(); ok {
		if err := therapistprofile.PsychologyLicenseValidator(v); err != nil {
			return &ValidationError{Name: "psychology_license", err: fmt.Errorf(`repo: validator failed for field "TherapistProfile.psychology_license": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Approach(); ok {
		if err := therapistprofile.ApproachValidator(v); err != nil {
			return &ValidationError{Name: "approach", err: fmt.Errorf(`repo: validator failed for field "TherapistProfile.approach": %w`, err)}
		}
	}
	if _u.mutation.MemberCleared() && len(_u.mutation.MemberIDs()) > 0 {
		return errors.New(`repo: clearing a required unique edge "TherapistProfile.member"`)
	}
	return nil
}

func (_u *TherapistProfileUpdateOne) sqlSave(ctx context.Context) (_node *TherapistProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(therapistprofile.Table, therapistprofile.Columns, sqlgraph.NewFieldSpec(therapistprofile.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`repo: missing "TherapistProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, therapistprofile.FieldID)
		for _, f := range fields {
			if !therapistprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("repo: invalid field %q for query", f)}
			}
			if f != therapistprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(therapistprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Education(); ok {
		_spec.SetField(therapistprofile.FieldEducation, field.TypeString, value)
	}
	if _u.mutation.EducationCleared() {
		_spec.ClearField(therapistprofile.FieldEducation, field.TypeString)
	}
	if value, ok := _u.mutation.PsychologyLicense(); ok {
		_spec.SetField(therapistprofile.FieldPsychologyLicense, field.TypeString, value)
	}
	if _u.mutation.PsychologyLicenseCleared() {
		_spec.ClearField(therapistprofile.FieldPsychologyLicense, field.TypeString)
	}
	if value, ok := _u.mutation.Approach(); ok {
		_spec.SetField(therapistprofile.FieldApproach, field.TypeString, value)
	}
	if _u.mutation.ApproachCleared() {
		_spec.ClearField(therapistprofile.FieldApproach, field.TypeString)
	}
	if value, ok := _u.mutation.Specialties(); ok {
		_spec.SetField(therapistprofile.FieldSpecialties, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecialties(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, therapistprofile.FieldSpecialties, value)
		})
	}
	if _u.mutation.SpecialtiesCleared() {
		_spec.ClearField(therapistprofile.FieldSpecialties, field.TypeJSON)
	}
	if value, ok := _u.mutation.Bio(); ok {
		_spec.SetField(therapistprofile.FieldBio, field.TypeString, value)
	}
	if _u.mutation.BioCleared() {
		_spec.ClearField(therapistprofile.FieldBio, field.TypeString)
	}
	if value, ok := _u.mutation.Rating(); ok {
		_spec.SetField(therapistprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRating(); ok {
		_spec.AddField(therapistprofile.FieldRating, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.SessionPrice(); ok {
		_spec.SetField(therapistprofile.FieldSessionPrice, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedSessionPrice(); ok {
		_spec.AddField(therapistprofile.FieldSessionPrice, field.TypeInt64, value)
	}
	if _u.mutation.SessionPriceCleared() {
		_spec.ClearField(therapistprofile.FieldSessionPrice, field.TypeInt64)
	}
	if value, ok := _u.mutation.SessionDurationMin(); ok {
		_spec.SetField(therapistprofile.FieldSessionDurationMin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSessionDurationMin(); ok {
		_spec.AddField(therapistprofile.FieldSessionDurationMin, field.TypeInt, value)
	}
	if _u.mutation.SessionDurationMinCleared() {
		_spec.ClearField(therapistprofile.FieldSessionDurationMin, field.TypeInt)
	}
	if value, ok := _u.mutation.IsAccepting(); ok {
		_spec.SetField(therapistprofile.FieldIsAccepting, field.TypeBool, value)
	}
	if _u.mutation.MemberCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   therapistprofile.MemberTable,
			Columns: []string{therapistprofile.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MemberIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   therapistprofile.MemberTable,
			Columns: []string{therapistprofile.MemberColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(clinicmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TherapistProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{therapistprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
