// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/Alijeyrad/simorq_backend/internal/repo/timeslot"
)

// TimeSlotDelete is the builder for deleting a TimeSlot entity.
type TimeSlotDelete struct {
	config
	hooks    []Hook
	mutation *TimeSlotMutation
}

// Where appends a list predicates to the TimeSlotDelete builder.
func (_d *TimeSlotDelete) Where(ps ...predicate.TimeSlot) *TimeSlotDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *TimeSlotDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TimeSlotDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *TimeSlotDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(timeslot.Table, sqlgraph.NewFieldSpec(timeslot.FieldID, field.TypeUUID))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// TimeSlotDeleteOne is the builder for deleting a single TimeSlot entity.
type TimeSlotDeleteOne struct {
	_d *TimeSlotDelete
}

// Where appends a list predicates to the TimeSlotDelete builder.
func (_d *TimeSlotDeleteOne) Where(ps ...predicate.TimeSlot) *TimeSlotDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *TimeSlotDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{timeslot.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *TimeSlotDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
