// Code generated by ent, DO NOT EDIT.

package repo

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Alijeyrad/simorq_backend/internal/repo/transaction"
	"github.com/Alijeyrad/simorq_backend/internal/repo/wallet"
	"github.com/google/uuid"
)

// Transaction is the model entity for the Transaction schema.
type Transaction struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// FK → wallets.id
	WalletID uuid.UUID `json:"wallet_id,omitempty"`
	// Type holds the value of the "type" field.
	Type transaction.Type `json:"type,omitempty"`
	// Amount in Rials (always positive)
	Amount int64 `json:"amount,omitempty"`
	// Wallet balance before this transaction
	BalanceBefore int64 `json:"balance_before,omitempty"`
	// Wallet balance after this transaction
	BalanceAfter int64 `json:"balance_after,omitempty"`
	// Type of the related entity (e.g. appointment, payment_request)
	EntityType *string `json:"entity_type,omitempty"`
	// ID of the related entity
	EntityID *uuid.UUID `json:"entity_id,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TransactionQuery when eager-loading is set.
	Edges        TransactionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TransactionEdges holds the relations/edges for other nodes in the graph.
type TransactionEdges struct {
	// Wallet holds the value of the wallet edge.
	Wallet *Wallet `json:"wallet,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// WalletOrErr returns the Wallet value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TransactionEdges) WalletOrErr() (*Wallet, error) {
	if e.Wallet != nil {
		return e.Wallet, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: wallet.Label}
	}
	return nil, &NotLoadedError{edge: "wallet"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Transaction) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case transaction.FieldEntityID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case transaction.FieldAmount, transaction.FieldBalanceBefore, transaction.FieldBalanceAfter:
			values[i] = new(sql.NullInt64)
		case transaction.FieldType, transaction.FieldEntityType, transaction.FieldDescription:
			values[i] = new(sql.NullString)
		case transaction.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case transaction.FieldID, transaction.FieldWalletID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Transaction fields.
func (_m *Transaction) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case transaction.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case transaction.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case transaction.FieldWalletID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field wallet_id", values[i])
			} else if value != nil {
				_m.WalletID = *value
			}
		case transaction.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = transaction.Type(value.String)
			}
		case transaction.FieldAmount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Int64
			}
		case transaction.FieldBalanceBefore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_before", values[i])
			} else if value.Valid {
				_m.BalanceBefore = value.Int64
			}
		case transaction.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = value.Int64
			}
		case transaction.FieldEntityType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field entity_type", values[i])
			} else if value.Valid {
				_m.EntityType = new(string)
				*_m.EntityType = value.String
			}
		case transaction.FieldEntityID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field entity_id", values[i])
			} else if value.Valid {
				_m.EntityID = new(uuid.UUID)
				*_m.EntityID = *value.S.(*uuid.UUID)
			}
		case transaction.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Transaction.
// This includes values selected through modifiers, order, etc.
func (_m *Transaction) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryWallet queries the "wallet" edge of the Transaction entity.
func (_m *Transaction) QueryWallet() *WalletQuery {
	return NewTransactionClient(_m.config).QueryWallet(_m)
}

// Update returns a builder for updating this Transaction.
// Note that you need to call Transaction.Unwrap() before calling this method if this Transaction
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Transaction) Update() *TransactionUpdateOne {
	return NewTransactionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Transaction entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Transaction) Unwrap() *Transaction {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("repo: Transaction is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Transaction) String() string {
	var builder strings.Builder
	builder.WriteString("Transaction(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("wallet_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.WalletID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", _m.Type))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("balance_before=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceBefore))
	builder.WriteString(", ")
	builder.WriteString("balance_after=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAfter))
	builder.WriteString(", ")
	if v := _m.EntityType; v != nil {
		builder.WriteString("entity_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.EntityID; v != nil {
		builder.WriteString("entity_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// Transactions is a parsable slice of Transaction.
type Transactions []*Transaction
