// Code generated by ent, DO NOT EDIT.

package repo

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/Alijeyrad/simorq_backend/internal/repo/transaction"
	"github.com/Alijeyrad/simorq_backend/internal/repo/wallet"
	"github.com/Alijeyrad/simorq_backend/internal/repo/withdrawalrequest"
	"github.com/google/uuid"
)

// WalletUpdate is the builder for updating Wallet entities.
type WalletUpdate struct {
	config
	hooks    []Hook
	mutation *WalletMutation
}

// Where appends a list predicates to the WalletUpdate builder.
func (_u *WalletUpdate) Where(ps ...predicate.Wallet) *WalletUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletUpdate) SetUpdatedAt(v time.Time) *WalletUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerType sets the "owner_type" field.
func (_u *WalletUpdate) SetOwnerType(v wallet.OwnerType) *WalletUpdate {
	_u.mutation.SetOwnerType(v)
	return _u
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableOwnerType(v *wallet.OwnerType) *WalletUpdate {
	if v != nil {
		_u.SetOwnerType(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *WalletUpdate) SetOwnerID(v uuid.UUID) *WalletUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableOwnerID(v *uuid.UUID) *WalletUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *WalletUpdate) SetBalance(v int64) *WalletUpdate {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableBalance(v *int64) *WalletUpdate {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *WalletUpdate) AddBalance(v int64) *WalletUpdate {
	_u.mutation.AddBalance(v)
	return _u
}

// SetIbanEncrypted sets the "iban_encrypted" field.
func (_u *WalletUpdate) SetIbanEncrypted(v string) *WalletUpdate {
	_u.mutation.SetIbanEncrypted(v)
	return _u
}

// SetNillableIbanEncrypted sets the "iban_encrypted" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableIbanEncrypted(v *string) *WalletUpdate {
	if v != nil {
		_u.SetIbanEncrypted(*v)
	}
	return _u
}

// ClearIbanEncrypted clears the value of the "iban_encrypted" field.
func (_u *WalletUpdate) ClearIbanEncrypted() *WalletUpdate {
	_u.mutation.ClearIbanEncrypted()
	return _u
}

// SetIbanHash sets the "iban_hash" field.
func (_u *WalletUpdate) SetIbanHash(v string) *WalletUpdate {
	_u.mutation.SetIbanHash(v)
	return _u
}

// SetNillableIbanHash sets the "iban_hash" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableIbanHash(v *string) *WalletUpdate {
	if v != nil {
		_u.SetIbanHash(*v)
	}
	return _u
}

// ClearIbanHash clears the value of the "iban_hash" field.
func (_u *WalletUpdate) ClearIbanHash() *WalletUpdate {
	_u.mutation.ClearIbanHash()
	return _u
}

// SetAccountHolder sets the "account_holder" field.
func (_u *WalletUpdate) SetAccountHolder(v string) *WalletUpdate {
	_u.mutation.SetAccountHolder(v)
	return _u
}

// SetNillableAccountHolder sets the "account_holder" field if the given value is not nil.
func (_u *WalletUpdate) SetNillableAccountHolder(v *string) *WalletUpdate {
	if v != nil {
		_u.SetAccountHolder(*v)
	}
	return _u
}

// ClearAccountHolder clears the value of the "account_holder" field.
func (_u *WalletUpdate) ClearAccountHolder() *WalletUpdate {
	_u.mutation.ClearAccountHolder()
	return _u
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *WalletUpdate) AddTransactionIDs(ids ...uuid.UUID) *WalletUpdate {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *WalletUpdate) AddTransactions(v ...*Transaction) *WalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the WithdrawalRequest entity by IDs.
func (_u *WalletUpdate) AddWithdrawalIDs(ids ...uuid.UUID) *WalletUpdate {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the WithdrawalRequest entity.
func (_u *WalletUpdate) AddWithdrawals(v ...*WithdrawalRequest) *WalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// Mutation returns the WalletMutation object of the builder.
func (_u *WalletUpdate) Mutation() *WalletMutation {
	return _u.mutation
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *WalletUpdate) ClearTransactions() *WalletUpdate {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *WalletUpdate) RemoveTransactionIDs(ids ...uuid.UUID) *WalletUpdate {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *WalletUpdate) RemoveTransactions(v ...*Transaction) *WalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the WithdrawalRequest entity.
func (_u *WalletUpdate) ClearWithdrawals() *WalletUpdate {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to WithdrawalRequest entities by IDs.
func (_u *WalletUpdate) RemoveWithdrawalIDs(ids ...uuid.UUID) *WalletUpdate {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to WithdrawalRequest entities.
func (_u *WalletUpdate) RemoveWithdrawals(v ...*WithdrawalRequest) *WalletUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WalletUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WalletUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletUpdate) check() error {
	if v, ok := _u.mutation.OwnerType(); ok {
		if err := wallet.OwnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "owner_type", err: fmt.Errorf(`repo: validator failed for field "Wallet.owner_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IbanEncrypted(); ok {
		if err := wallet.IbanEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "iban_encrypted", err: fmt.Errorf(`repo: validator failed for field "Wallet.iban_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IbanHash(); ok {
		if err := wallet.IbanHashValidator(v); err != nil {
			return &ValidationError{Name: "iban_hash", err: fmt.Errorf(`repo: validator failed for field "Wallet.iban_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountHolder(); ok {
		if err := wallet.AccountHolderValidator(v); err != nil {
			return &ValidationError{Name: "account_holder", err: fmt.Errorf(`repo: validator failed for field "Wallet.account_holder": %w`, err)}
		}
	}
	return nil
}

func (_u *WalletUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerType(); ok {
		_spec.SetField(wallet.FieldOwnerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(wallet.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IbanEncrypted(); ok {
		_spec.SetField(wallet.FieldIbanEncrypted, field.TypeString, value)
	}
	if _u.mutation.IbanEncryptedCleared() {
		_spec.ClearField(wallet.FieldIbanEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.IbanHash(); ok {
		_spec.SetField(wallet.FieldIbanHash, field.TypeString, value)
	}
	if _u.mutation.IbanHashCleared() {
		_spec.ClearField(wallet.FieldIbanHash, field.TypeString)
	}
	if value, ok := _u.mutation.AccountHolder(); ok {
		_spec.SetField(wallet.FieldAccountHolder, field.TypeString, value)
	}
	if _u.mutation.AccountHolderCleared() {
		_spec.ClearField(wallet.FieldAccountHolder, field.TypeString)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.TransactionsTable,
			Columns: []string{wallet.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.TransactionsTable,
			Columns: []string{wallet.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.TransactionsTable,
			Columns: []string{wallet.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.WithdrawalsTable,
			Columns: []string{wallet.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawalrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.WithdrawalsTable,
			Columns: []string{wallet.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawalrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.WithdrawalsTable,
			Columns: []string{wallet.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawalrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WalletUpdateOne is the builder for updating a single Wallet entity.
type WalletUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WalletMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WalletUpdateOne) SetUpdatedAt(v time.Time) *WalletUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetOwnerType sets the "owner_type" field.
func (_u *WalletUpdateOne) SetOwnerType(v wallet.OwnerType) *WalletUpdateOne {
	_u.mutation.SetOwnerType(v)
	return _u
}

// SetNillableOwnerType sets the "owner_type" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableOwnerType(v *wallet.OwnerType) *WalletUpdateOne {
	if v != nil {
		_u.SetOwnerType(*v)
	}
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *WalletUpdateOne) SetOwnerID(v uuid.UUID) *WalletUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableOwnerID(v *uuid.UUID) *WalletUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetBalance sets the "balance" field.
func (_u *WalletUpdateOne) SetBalance(v int64) *WalletUpdateOne {
	_u.mutation.ResetBalance()
	_u.mutation.SetBalance(v)
	return _u
}

// SetNillableBalance sets the "balance" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableBalance(v *int64) *WalletUpdateOne {
	if v != nil {
		_u.SetBalance(*v)
	}
	return _u
}

// AddBalance adds value to the "balance" field.
func (_u *WalletUpdateOne) AddBalance(v int64) *WalletUpdateOne {
	_u.mutation.AddBalance(v)
	return _u
}

// SetIbanEncrypted sets the "iban_encrypted" field.
func (_u *WalletUpdateOne) SetIbanEncrypted(v string) *WalletUpdateOne {
	_u.mutation.SetIbanEncrypted(v)
	return _u
}

// SetNillableIbanEncrypted sets the "iban_encrypted" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableIbanEncrypted(v *string) *WalletUpdateOne {
	if v != nil {
		_u.SetIbanEncrypted(*v)
	}
	return _u
}

// ClearIbanEncrypted clears the value of the "iban_encrypted" field.
func (_u *WalletUpdateOne) ClearIbanEncrypted() *WalletUpdateOne {
	_u.mutation.ClearIbanEncrypted()
	return _u
}

// SetIbanHash sets the "iban_hash" field.
func (_u *WalletUpdateOne) SetIbanHash(v string) *WalletUpdateOne {
	_u.mutation.SetIbanHash(v)
	return _u
}

// SetNillableIbanHash sets the "iban_hash" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableIbanHash(v *string) *WalletUpdateOne {
	if v != nil {
		_u.SetIbanHash(*v)
	}
	return _u
}

// ClearIbanHash clears the value of the "iban_hash" field.
func (_u *WalletUpdateOne) ClearIbanHash() *WalletUpdateOne {
	_u.mutation.ClearIbanHash()
	return _u
}

// SetAccountHolder sets the "account_holder" field.
func (_u *WalletUpdateOne) SetAccountHolder(v string) *WalletUpdateOne {
	_u.mutation.SetAccountHolder(v)
	return _u
}

// SetNillableAccountHolder sets the "account_holder" field if the given value is not nil.
func (_u *WalletUpdateOne) SetNillableAccountHolder(v *string) *WalletUpdateOne {
	if v != nil {
		_u.SetAccountHolder(*v)
	}
	return _u
}

// ClearAccountHolder clears the value of the "account_holder" field.
func (_u *WalletUpdateOne) ClearAccountHolder() *WalletUpdateOne {
	_u.mutation.ClearAccountHolder()
	return _u
}

// AddTransactionIDs adds the "transactions" edge to the Transaction entity by IDs.
func (_u *WalletUpdateOne) AddTransactionIDs(ids ...uuid.UUID) *WalletUpdateOne {
	_u.mutation.AddTransactionIDs(ids...)
	return _u
}

// AddTransactions adds the "transactions" edges to the Transaction entity.
func (_u *WalletUpdateOne) AddTransactions(v ...*Transaction) *WalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddTransactionIDs(ids...)
}

// AddWithdrawalIDs adds the "withdrawals" edge to the WithdrawalRequest entity by IDs.
func (_u *WalletUpdateOne) AddWithdrawalIDs(ids ...uuid.UUID) *WalletUpdateOne {
	_u.mutation.AddWithdrawalIDs(ids...)
	return _u
}

// AddWithdrawals adds the "withdrawals" edges to the WithdrawalRequest entity.
func (_u *WalletUpdateOne) AddWithdrawals(v ...*WithdrawalRequest) *WalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddWithdrawalIDs(ids...)
}

// Mutation returns the WalletMutation object of the builder.
func (_u *WalletUpdateOne) Mutation() *WalletMutation {
	return _u.mutation
}

// ClearTransactions clears all "transactions" edges to the Transaction entity.
func (_u *WalletUpdateOne) ClearTransactions() *WalletUpdateOne {
	_u.mutation.ClearTransactions()
	return _u
}

// RemoveTransactionIDs removes the "transactions" edge to Transaction entities by IDs.
func (_u *WalletUpdateOne) RemoveTransactionIDs(ids ...uuid.UUID) *WalletUpdateOne {
	_u.mutation.RemoveTransactionIDs(ids...)
	return _u
}

// RemoveTransactions removes "transactions" edges to Transaction entities.
func (_u *WalletUpdateOne) RemoveTransactions(v ...*Transaction) *WalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveTransactionIDs(ids...)
}

// ClearWithdrawals clears all "withdrawals" edges to the WithdrawalRequest entity.
func (_u *WalletUpdateOne) ClearWithdrawals() *WalletUpdateOne {
	_u.mutation.ClearWithdrawals()
	return _u
}

// RemoveWithdrawalIDs removes the "withdrawals" edge to WithdrawalRequest entities by IDs.
func (_u *WalletUpdateOne) RemoveWithdrawalIDs(ids ...uuid.UUID) *WalletUpdateOne {
	_u.mutation.RemoveWithdrawalIDs(ids...)
	return _u
}

// RemoveWithdrawals removes "withdrawals" edges to WithdrawalRequest entities.
func (_u *WalletUpdateOne) RemoveWithdrawals(v ...*WithdrawalRequest) *WalletUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveWithdrawalIDs(ids...)
}

// Where appends a list predicates to the WalletUpdate builder.
func (_u *WalletUpdateOne) Where(ps ...predicate.Wallet) *WalletUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WalletUpdateOne) Select(field string, fields ...string) *WalletUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Wallet entity.
func (_u *WalletUpdateOne) Save(ctx context.Context) (*Wallet, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WalletUpdateOne) SaveX(ctx context.Context) *Wallet {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WalletUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WalletUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *WalletUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := wallet.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *WalletUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerType(); ok {
		if err := wallet.OwnerTypeValidator(v); err != nil {
			return &ValidationError{Name: "owner_type", err: fmt.Errorf(`repo: validator failed for field "Wallet.owner_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IbanEncrypted(); ok {
		if err := wallet.IbanEncryptedValidator(v); err != nil {
			return &ValidationError{Name: "iban_encrypted", err: fmt.Errorf(`repo: validator failed for field "Wallet.iban_encrypted": %w`, err)}
		}
	}
	if v, ok := _u.mutation.IbanHash(); ok {
		if err := wallet.IbanHashValidator(v); err != nil {
			return &ValidationError{Name: "iban_hash", err: fmt.Errorf(`repo: validator failed for field "Wallet.iban_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountHolder(); ok {
		if err := wallet.AccountHolderValidator(v); err != nil {
			return &ValidationError{Name: "account_holder", err: fmt.Errorf(`repo: validator failed for field "Wallet.account_holder": %w`, err)}
		}
	}
	return nil
}

func (_u *WalletUpdateOne) sqlSave(ctx context.Context) (_node *Wallet, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(wallet.Table, wallet.Columns, sqlgraph.NewFieldSpec(wallet.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`repo: missing "Wallet.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, wallet.FieldID)
		for _, f := range fields {
			if !wallet.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("repo: invalid field %q for query", f)}
			}
			if f != wallet.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(wallet.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.OwnerType(); ok {
		_spec.SetField(wallet.FieldOwnerType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(wallet.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Balance(); ok {
		_spec.SetField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedBalance(); ok {
		_spec.AddField(wallet.FieldBalance, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.IbanEncrypted(); ok {
		_spec.SetField(wallet.FieldIbanEncrypted, field.TypeString, value)
	}
	if _u.mutation.IbanEncryptedCleared() {
		_spec.ClearField(wallet.FieldIbanEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.IbanHash(); ok {
		_spec.SetField(wallet.FieldIbanHash, field.TypeString, value)
	}
	if _u.mutation.IbanHashCleared() {
		_spec.ClearField(wallet.FieldIbanHash, field.TypeString)
	}
	if value, ok := _u.mutation.AccountHolder(); ok {
		_spec.SetField(wallet.FieldAccountHolder, field.TypeString, value)
	}
	if _u.mutation.AccountHolderCleared() {
		_spec.ClearField(wallet.FieldAccountHolder, field.TypeString)
	}
	if _u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.TransactionsTable,
			Columns: []string{wallet.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedTransactionsIDs(); len(nodes) > 0 && !_u.mutation.TransactionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.TransactionsTable,
			Columns: []string{wallet.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.TransactionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.TransactionsTable,
			Columns: []string{wallet.TransactionsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(transaction.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.WithdrawalsTable,
			Columns: []string{wallet.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawalrequest.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedWithdrawalsIDs(); len(nodes) > 0 && !_u.mutation.WithdrawalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.WithdrawalsTable,
			Columns: []string{wallet.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawalrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.WithdrawalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   wallet.WithdrawalsTable,
			Columns: []string{wallet.WithdrawalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(withdrawalrequest.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Wallet{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{wallet.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
