// Code generated by ent, DO NOT EDIT.

package timeslot

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the timeslot type in the database.
	Label = "time_slot"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldTherapistID holds the string denoting the therapist_id field in the database.
	FieldTherapistID = "therapist_id"
	// FieldClinicID holds the string denoting the clinic_id field in the database.
	FieldClinicID = "clinic_id"
	// FieldStartTime holds the string denoting the start_time field in the database.
	FieldStartTime = "start_time"
	// FieldEndTime holds the string denoting the end_time field in the database.
	FieldEndTime = "end_time"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldSessionPrice holds the string denoting the session_price field in the database.
	FieldSessionPrice = "session_price"
	// FieldReservationFee holds the string denoting the reservation_fee field in the database.
	FieldReservationFee = "reservation_fee"
	// FieldIsRecurring holds the string denoting the is_recurring field in the database.
	FieldIsRecurring = "is_recurring"
	// FieldRecurringRuleID holds the string denoting the recurring_rule_id field in the database.
	FieldRecurringRuleID = "recurring_rule_id"
	// Table holds the table name of the timeslot in the database.
	Table = "time_slots"
)

// Columns holds all SQL columns for timeslot fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldTherapistID,
	FieldClinicID,
	FieldStartTime,
	FieldEndTime,
	FieldStatus,
	FieldSessionPrice,
	FieldReservationFee,
	FieldIsRecurring,
	FieldRecurringRuleID,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultIsRecurring holds the default value on creation for the "is_recurring" field.
	DefaultIsRecurring bool
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// Status defines the type for the "status" enum field.
type Status string

// StatusAvailable is the default value of the Status enum.
const DefaultStatus = StatusAvailable

// Status values.
const (
	StatusAvailable Status = "available"
	StatusBooked    Status = "booked"
	StatusBlocked   Status = "blocked"
	StatusCancelled Status = "cancelled"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusAvailable, StatusBooked, StatusBlocked, StatusCancelled:
		return nil
	default:
		return fmt.Errorf("timeslot: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the TimeSlot queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByTherapistID orders the results by the therapist_id field.
func ByTherapistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTherapistID, opts...).ToFunc()
}

// ByClinicID orders the results by the clinic_id field.
func ByClinicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClinicID, opts...).ToFunc()
}

// ByStartTime orders the results by the start_time field.
func ByStartTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartTime, opts...).ToFunc()
}

// ByEndTime orders the results by the end_time field.
func ByEndTime(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndTime, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// BySessionPrice orders the results by the session_price field.
func BySessionPrice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionPrice, opts...).ToFunc()
}

// ByReservationFee orders the results by the reservation_fee field.
func ByReservationFee(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReservationFee, opts...).ToFunc()
}

// ByIsRecurring orders the results by the is_recurring field.
func ByIsRecurring(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsRecurring, opts...).ToFunc()
}

// ByRecurringRuleID orders the results by the recurring_rule_id field.
func ByRecurringRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRecurringRuleID, opts...).ToFunc()
}
