// Code generated by ent, DO NOT EDIT.

package patientprescription

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the patientprescription type in the database.
	Label = "patient_prescription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldPatientID holds the string denoting the patient_id field in the database.
	FieldPatientID = "patient_id"
	// FieldClinicID holds the string denoting the clinic_id field in the database.
	FieldClinicID = "clinic_id"
	// FieldTherapistID holds the string denoting the therapist_id field in the database.
	FieldTherapistID = "therapist_id"
	// FieldTitle holds the string denoting the title field in the database.
	FieldTitle = "title"
	// FieldNotes holds the string denoting the notes field in the database.
	FieldNotes = "notes"
	// FieldFileKey holds the string denoting the file_key field in the database.
	FieldFileKey = "file_key"
	// FieldFileName holds the string denoting the file_name field in the database.
	FieldFileName = "file_name"
	// FieldPrescribedDate holds the string denoting the prescribed_date field in the database.
	FieldPrescribedDate = "prescribed_date"
	// EdgePatient holds the string denoting the patient edge name in mutations.
	EdgePatient = "patient"
	// EdgeTherapist holds the string denoting the therapist edge name in mutations.
	EdgeTherapist = "therapist"
	// Table holds the table name of the patientprescription in the database.
	Table = "patient_prescriptions"
	// PatientTable is the table that holds the patient relation/edge.
	PatientTable = "patient_prescriptions"
	// PatientInverseTable is the table name for the Patient entity.
	// It exists in this package in order to avoid circular dependency with the "patient" package.
	PatientInverseTable = "patients"
	// PatientColumn is the table column denoting the patient relation/edge.
	PatientColumn = "patient_id"
	// TherapistTable is the table that holds the therapist relation/edge.
	TherapistTable = "patient_prescriptions"
	// TherapistInverseTable is the table name for the ClinicMember entity.
	// It exists in this package in order to avoid circular dependency with the "clinicmember" package.
	TherapistInverseTable = "clinic_members"
	// TherapistColumn is the table column denoting the therapist relation/edge.
	TherapistColumn = "therapist_id"
)

// Columns holds all SQL columns for patientprescription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldPatientID,
	FieldClinicID,
	FieldTherapistID,
	FieldTitle,
	FieldNotes,
	FieldFileKey,
	FieldFileName,
	FieldPrescribedDate,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// TitleValidator is a validator for the "title" field. It is called by the builders before save.
	TitleValidator func(string) error
	// FileKeyValidator is a validator for the "file_key" field. It is called by the builders before save.
	FileKeyValidator func(string) error
	// FileNameValidator is a validator for the "file_name" field. It is called by the builders before save.
	FileNameValidator func(string) error
	// DefaultPrescribedDate holds the default value on creation for the "prescribed_date" field.
	DefaultPrescribedDate func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the PatientPrescription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPatientID orders the results by the patient_id field.
func ByPatientID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPatientID, opts...).ToFunc()
}

// ByClinicID orders the results by the clinic_id field.
func ByClinicID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldClinicID, opts...).ToFunc()
}

// ByTherapistID orders the results by the therapist_id field.
func ByTherapistID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTherapistID, opts...).ToFunc()
}

// ByTitle orders the results by the title field.
func ByTitle(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTitle, opts...).ToFunc()
}

// ByNotes orders the results by the notes field.
func ByNotes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotes, opts...).ToFunc()
}

// ByFileKey orders the results by the file_key field.
func ByFileKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileKey, opts...).ToFunc()
}

// ByFileName orders the results by the file_name field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByPrescribedDate orders the results by the prescribed_date field.
func ByPrescribedDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPrescribedDate, opts...).ToFunc()
}

// ByPatientField orders the results by patient field.
func ByPatientField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPatientStep(), sql.OrderByField(field, opts...))
	}
}

// ByTherapistField orders the results by therapist field.
func ByTherapistField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTherapistStep(), sql.OrderByField(field, opts...))
	}
}
func newPatientStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PatientInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
	)
}
func newTherapistStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TherapistInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, TherapistTable, TherapistColumn),
	)
}
