// Code generated by ent, DO NOT EDIT.

package clinicsettings

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// ClinicID applies equality check predicate on the "clinic_id" field. It's identical to ClinicIDEQ.
func ClinicID(v uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldClinicID, v))
}

// ReservationFeeAmount applies equality check predicate on the "reservation_fee_amount" field. It's identical to ReservationFeeAmountEQ.
func ReservationFeeAmount(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldReservationFeeAmount, v))
}

// ReservationFeePercent applies equality check predicate on the "reservation_fee_percent" field. It's identical to ReservationFeePercentEQ.
func ReservationFeePercent(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldReservationFeePercent, v))
}

// CancellationWindowHours applies equality check predicate on the "cancellation_window_hours" field. It's identical to CancellationWindowHoursEQ.
func CancellationWindowHours(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCancellationWindowHours, v))
}

// CancellationFeeAmount applies equality check predicate on the "cancellation_fee_amount" field. It's identical to CancellationFeeAmountEQ.
func CancellationFeeAmount(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCancellationFeeAmount, v))
}

// CancellationFeePercent applies equality check predicate on the "cancellation_fee_percent" field. It's identical to CancellationFeePercentEQ.
func CancellationFeePercent(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCancellationFeePercent, v))
}

// AllowClientSelfBook applies equality check predicate on the "allow_client_self_book" field. It's identical to AllowClientSelfBookEQ.
func AllowClientSelfBook(v bool) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldAllowClientSelfBook, v))
}

// DefaultSessionDurationMin applies equality check predicate on the "default_session_duration_min" field. It's identical to DefaultSessionDurationMinEQ.
func DefaultSessionDurationMin(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionPrice applies equality check predicate on the "default_session_price" field. It's identical to DefaultSessionPriceEQ.
func DefaultSessionPrice(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldDefaultSessionPrice, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// ClinicIDEQ applies the EQ predicate on the "clinic_id" field.
func ClinicIDEQ(v uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldClinicID, v))
}

// ClinicIDNEQ applies the NEQ predicate on the "clinic_id" field.
func ClinicIDNEQ(v uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldClinicID, v))
}

// ClinicIDIn applies the In predicate on the "clinic_id" field.
func ClinicIDIn(vs ...uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldClinicID, vs...))
}

// ClinicIDNotIn applies the NotIn predicate on the "clinic_id" field.
func ClinicIDNotIn(vs ...uuid.UUID) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldClinicID, vs...))
}

// ReservationFeeAmountEQ applies the EQ predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountEQ(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldReservationFeeAmount, v))
}

// ReservationFeeAmountNEQ applies the NEQ predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountNEQ(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldReservationFeeAmount, v))
}

// ReservationFeeAmountIn applies the In predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountIn(vs ...int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldReservationFeeAmount, vs...))
}

// ReservationFeeAmountNotIn applies the NotIn predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountNotIn(vs ...int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldReservationFeeAmount, vs...))
}

// ReservationFeeAmountGT applies the GT predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountGT(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldReservationFeeAmount, v))
}

// ReservationFeeAmountGTE applies the GTE predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountGTE(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldReservationFeeAmount, v))
}

// ReservationFeeAmountLT applies the LT predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountLT(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldReservationFeeAmount, v))
}

// ReservationFeeAmountLTE applies the LTE predicate on the "reservation_fee_amount" field.
func ReservationFeeAmountLTE(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldReservationFeeAmount, v))
}

// ReservationFeePercentEQ applies the EQ predicate on the "reservation_fee_percent" field.
func ReservationFeePercentEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldReservationFeePercent, v))
}

// ReservationFeePercentNEQ applies the NEQ predicate on the "reservation_fee_percent" field.
func ReservationFeePercentNEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldReservationFeePercent, v))
}

// ReservationFeePercentIn applies the In predicate on the "reservation_fee_percent" field.
func ReservationFeePercentIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldReservationFeePercent, vs...))
}

// ReservationFeePercentNotIn applies the NotIn predicate on the "reservation_fee_percent" field.
func ReservationFeePercentNotIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldReservationFeePercent, vs...))
}

// ReservationFeePercentGT applies the GT predicate on the "reservation_fee_percent" field.
func ReservationFeePercentGT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldReservationFeePercent, v))
}

// ReservationFeePercentGTE applies the GTE predicate on the "reservation_fee_percent" field.
func ReservationFeePercentGTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldReservationFeePercent, v))
}

// ReservationFeePercentLT applies the LT predicate on the "reservation_fee_percent" field.
func ReservationFeePercentLT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldReservationFeePercent, v))
}

// ReservationFeePercentLTE applies the LTE predicate on the "reservation_fee_percent" field.
func ReservationFeePercentLTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldReservationFeePercent, v))
}

// CancellationWindowHoursEQ applies the EQ predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCancellationWindowHours, v))
}

// CancellationWindowHoursNEQ applies the NEQ predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursNEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldCancellationWindowHours, v))
}

// CancellationWindowHoursIn applies the In predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldCancellationWindowHours, vs...))
}

// CancellationWindowHoursNotIn applies the NotIn predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursNotIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldCancellationWindowHours, vs...))
}

// CancellationWindowHoursGT applies the GT predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursGT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldCancellationWindowHours, v))
}

// CancellationWindowHoursGTE applies the GTE predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursGTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldCancellationWindowHours, v))
}

// CancellationWindowHoursLT applies the LT predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursLT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldCancellationWindowHours, v))
}

// CancellationWindowHoursLTE applies the LTE predicate on the "cancellation_window_hours" field.
func CancellationWindowHoursLTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldCancellationWindowHours, v))
}

// CancellationFeeAmountEQ applies the EQ predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountEQ(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCancellationFeeAmount, v))
}

// CancellationFeeAmountNEQ applies the NEQ predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountNEQ(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldCancellationFeeAmount, v))
}

// CancellationFeeAmountIn applies the In predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountIn(vs ...int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldCancellationFeeAmount, vs...))
}

// CancellationFeeAmountNotIn applies the NotIn predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountNotIn(vs ...int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldCancellationFeeAmount, vs...))
}

// CancellationFeeAmountGT applies the GT predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountGT(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldCancellationFeeAmount, v))
}

// CancellationFeeAmountGTE applies the GTE predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountGTE(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldCancellationFeeAmount, v))
}

// CancellationFeeAmountLT applies the LT predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountLT(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldCancellationFeeAmount, v))
}

// CancellationFeeAmountLTE applies the LTE predicate on the "cancellation_fee_amount" field.
func CancellationFeeAmountLTE(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldCancellationFeeAmount, v))
}

// CancellationFeePercentEQ applies the EQ predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldCancellationFeePercent, v))
}

// CancellationFeePercentNEQ applies the NEQ predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentNEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldCancellationFeePercent, v))
}

// CancellationFeePercentIn applies the In predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldCancellationFeePercent, vs...))
}

// CancellationFeePercentNotIn applies the NotIn predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentNotIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldCancellationFeePercent, vs...))
}

// CancellationFeePercentGT applies the GT predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentGT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldCancellationFeePercent, v))
}

// CancellationFeePercentGTE applies the GTE predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentGTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldCancellationFeePercent, v))
}

// CancellationFeePercentLT applies the LT predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentLT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldCancellationFeePercent, v))
}

// CancellationFeePercentLTE applies the LTE predicate on the "cancellation_fee_percent" field.
func CancellationFeePercentLTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldCancellationFeePercent, v))
}

// AllowClientSelfBookEQ applies the EQ predicate on the "allow_client_self_book" field.
func AllowClientSelfBookEQ(v bool) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldAllowClientSelfBook, v))
}

// AllowClientSelfBookNEQ applies the NEQ predicate on the "allow_client_self_book" field.
func AllowClientSelfBookNEQ(v bool) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldAllowClientSelfBook, v))
}

// DefaultSessionDurationMinEQ applies the EQ predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionDurationMinNEQ applies the NEQ predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinNEQ(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionDurationMinIn applies the In predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldDefaultSessionDurationMin, vs...))
}

// DefaultSessionDurationMinNotIn applies the NotIn predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinNotIn(vs ...int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldDefaultSessionDurationMin, vs...))
}

// DefaultSessionDurationMinGT applies the GT predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinGT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionDurationMinGTE applies the GTE predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinGTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionDurationMinLT applies the LT predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinLT(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionDurationMinLTE applies the LTE predicate on the "default_session_duration_min" field.
func DefaultSessionDurationMinLTE(v int) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldDefaultSessionDurationMin, v))
}

// DefaultSessionPriceEQ applies the EQ predicate on the "default_session_price" field.
func DefaultSessionPriceEQ(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldEQ(FieldDefaultSessionPrice, v))
}

// DefaultSessionPriceNEQ applies the NEQ predicate on the "default_session_price" field.
func DefaultSessionPriceNEQ(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNEQ(FieldDefaultSessionPrice, v))
}

// DefaultSessionPriceIn applies the In predicate on the "default_session_price" field.
func DefaultSessionPriceIn(vs ...int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIn(FieldDefaultSessionPrice, vs...))
}

// DefaultSessionPriceNotIn applies the NotIn predicate on the "default_session_price" field.
func DefaultSessionPriceNotIn(vs ...int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotIn(FieldDefaultSessionPrice, vs...))
}

// DefaultSessionPriceGT applies the GT predicate on the "default_session_price" field.
func DefaultSessionPriceGT(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGT(FieldDefaultSessionPrice, v))
}

// DefaultSessionPriceGTE applies the GTE predicate on the "default_session_price" field.
func DefaultSessionPriceGTE(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldGTE(FieldDefaultSessionPrice, v))
}

// DefaultSessionPriceLT applies the LT predicate on the "default_session_price" field.
func DefaultSessionPriceLT(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLT(FieldDefaultSessionPrice, v))
}

// DefaultSessionPriceLTE applies the LTE predicate on the "default_session_price" field.
func DefaultSessionPriceLTE(v int64) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldLTE(FieldDefaultSessionPrice, v))
}

// WorkingHoursIsNil applies the IsNil predicate on the "working_hours" field.
func WorkingHoursIsNil() predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldIsNull(FieldWorkingHours))
}

// WorkingHoursNotNil applies the NotNil predicate on the "working_hours" field.
func WorkingHoursNotNil() predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.FieldNotNull(FieldWorkingHours))
}

// HasClinic applies the HasEdge predicate on the "clinic" edge.
func HasClinic() predicate.ClinicSettings {
	return predicate.ClinicSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, ClinicTable, ClinicColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasClinicWith applies the HasEdge predicate on the "clinic" edge with a given conditions (other predicates).
func HasClinicWith(preds ...predicate.Clinic) predicate.ClinicSettings {
	return predicate.ClinicSettings(func(s *sql.Selector) {
		step := newClinicStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ClinicSettings) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ClinicSettings) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ClinicSettings) predicate.ClinicSettings {
	return predicate.ClinicSettings(sql.NotPredicates(p))
}
