// Code generated by ent, DO NOT EDIT.

package patientreport

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// PatientID applies equality check predicate on the "patient_id" field. It's identical to PatientIDEQ.
func PatientID(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldPatientID, v))
}

// ClinicID applies equality check predicate on the "clinic_id" field. It's identical to ClinicIDEQ.
func ClinicID(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldClinicID, v))
}

// TherapistID applies equality check predicate on the "therapist_id" field. It's identical to TherapistIDEQ.
func TherapistID(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldTherapistID, v))
}

// AppointmentID applies equality check predicate on the "appointment_id" field. It's identical to AppointmentIDEQ.
func AppointmentID(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldAppointmentID, v))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldTitle, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldContent, v))
}

// ReportDate applies equality check predicate on the "report_date" field. It's identical to ReportDateEQ.
func ReportDate(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldReportDate, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldUpdatedAt, v))
}

// PatientIDEQ applies the EQ predicate on the "patient_id" field.
func PatientIDEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldPatientID, v))
}

// PatientIDNEQ applies the NEQ predicate on the "patient_id" field.
func PatientIDNEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldPatientID, v))
}

// PatientIDIn applies the In predicate on the "patient_id" field.
func PatientIDIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldPatientID, vs...))
}

// PatientIDNotIn applies the NotIn predicate on the "patient_id" field.
func PatientIDNotIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldPatientID, vs...))
}

// ClinicIDEQ applies the EQ predicate on the "clinic_id" field.
func ClinicIDEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldClinicID, v))
}

// ClinicIDNEQ applies the NEQ predicate on the "clinic_id" field.
func ClinicIDNEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldClinicID, v))
}

// ClinicIDIn applies the In predicate on the "clinic_id" field.
func ClinicIDIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldClinicID, vs...))
}

// ClinicIDNotIn applies the NotIn predicate on the "clinic_id" field.
func ClinicIDNotIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldClinicID, vs...))
}

// ClinicIDGT applies the GT predicate on the "clinic_id" field.
func ClinicIDGT(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldClinicID, v))
}

// ClinicIDGTE applies the GTE predicate on the "clinic_id" field.
func ClinicIDGTE(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldClinicID, v))
}

// ClinicIDLT applies the LT predicate on the "clinic_id" field.
func ClinicIDLT(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldClinicID, v))
}

// ClinicIDLTE applies the LTE predicate on the "clinic_id" field.
func ClinicIDLTE(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldClinicID, v))
}

// TherapistIDEQ applies the EQ predicate on the "therapist_id" field.
func TherapistIDEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldTherapistID, v))
}

// TherapistIDNEQ applies the NEQ predicate on the "therapist_id" field.
func TherapistIDNEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldTherapistID, v))
}

// TherapistIDIn applies the In predicate on the "therapist_id" field.
func TherapistIDIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldTherapistID, vs...))
}

// TherapistIDNotIn applies the NotIn predicate on the "therapist_id" field.
func TherapistIDNotIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldTherapistID, vs...))
}

// AppointmentIDEQ applies the EQ predicate on the "appointment_id" field.
func AppointmentIDEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldAppointmentID, v))
}

// AppointmentIDNEQ applies the NEQ predicate on the "appointment_id" field.
func AppointmentIDNEQ(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldAppointmentID, v))
}

// AppointmentIDIn applies the In predicate on the "appointment_id" field.
func AppointmentIDIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldAppointmentID, vs...))
}

// AppointmentIDNotIn applies the NotIn predicate on the "appointment_id" field.
func AppointmentIDNotIn(vs ...uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldAppointmentID, vs...))
}

// AppointmentIDGT applies the GT predicate on the "appointment_id" field.
func AppointmentIDGT(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldAppointmentID, v))
}

// AppointmentIDGTE applies the GTE predicate on the "appointment_id" field.
func AppointmentIDGTE(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldAppointmentID, v))
}

// AppointmentIDLT applies the LT predicate on the "appointment_id" field.
func AppointmentIDLT(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldAppointmentID, v))
}

// AppointmentIDLTE applies the LTE predicate on the "appointment_id" field.
func AppointmentIDLTE(v uuid.UUID) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldAppointmentID, v))
}

// AppointmentIDIsNil applies the IsNil predicate on the "appointment_id" field.
func AppointmentIDIsNil() predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIsNull(FieldAppointmentID))
}

// AppointmentIDNotNil applies the NotNil predicate on the "appointment_id" field.
func AppointmentIDNotNil() predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotNull(FieldAppointmentID))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleIsNil applies the IsNil predicate on the "title" field.
func TitleIsNil() predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIsNull(FieldTitle))
}

// TitleNotNil applies the NotNil predicate on the "title" field.
func TitleNotNil() predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotNull(FieldTitle))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldContainsFold(FieldTitle, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldHasSuffix(FieldContent, v))
}

// ContentIsNil applies the IsNil predicate on the "content" field.
func ContentIsNil() predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIsNull(FieldContent))
}

// ContentNotNil applies the NotNil predicate on the "content" field.
func ContentNotNil() predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotNull(FieldContent))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldContainsFold(FieldContent, v))
}

// ReportDateEQ applies the EQ predicate on the "report_date" field.
func ReportDateEQ(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldEQ(FieldReportDate, v))
}

// ReportDateNEQ applies the NEQ predicate on the "report_date" field.
func ReportDateNEQ(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNEQ(FieldReportDate, v))
}

// ReportDateIn applies the In predicate on the "report_date" field.
func ReportDateIn(vs ...time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldIn(FieldReportDate, vs...))
}

// ReportDateNotIn applies the NotIn predicate on the "report_date" field.
func ReportDateNotIn(vs ...time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldNotIn(FieldReportDate, vs...))
}

// ReportDateGT applies the GT predicate on the "report_date" field.
func ReportDateGT(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGT(FieldReportDate, v))
}

// ReportDateGTE applies the GTE predicate on the "report_date" field.
func ReportDateGTE(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldGTE(FieldReportDate, v))
}

// ReportDateLT applies the LT predicate on the "report_date" field.
func ReportDateLT(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLT(FieldReportDate, v))
}

// ReportDateLTE applies the LTE predicate on the "report_date" field.
func ReportDateLTE(v time.Time) predicate.PatientReport {
	return predicate.PatientReport(sql.FieldLTE(FieldReportDate, v))
}

// HasPatient applies the HasEdge predicate on the "patient" edge.
func HasPatient() predicate.PatientReport {
	return predicate.PatientReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PatientTable, PatientColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPatientWith applies the HasEdge predicate on the "patient" edge with a given conditions (other predicates).
func HasPatientWith(preds ...predicate.Patient) predicate.PatientReport {
	return predicate.PatientReport(func(s *sql.Selector) {
		step := newPatientStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasTherapist applies the HasEdge predicate on the "therapist" edge.
func HasTherapist() predicate.PatientReport {
	return predicate.PatientReport(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, TherapistTable, TherapistColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasTherapistWith applies the HasEdge predicate on the "therapist" edge with a given conditions (other predicates).
func HasTherapistWith(preds ...predicate.ClinicMember) predicate.PatientReport {
	return predicate.PatientReport(func(s *sql.Selector) {
		step := newTherapistStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PatientReport) predicate.PatientReport {
	return predicate.PatientReport(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PatientReport) predicate.PatientReport {
	return predicate.PatientReport(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PatientReport) predicate.PatientReport {
	return predicate.PatientReport(sql.NotPredicates(p))
}
