// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/Alijeyrad/simorq_backend/internal/repo"
)

// The AppointmentFunc type is an adapter to allow the use of ordinary
// function as Appointment mutator.
type AppointmentFunc func(context.Context, *repo.AppointmentMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f AppointmentFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.AppointmentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.AppointmentMutation", m)
}

// The ClinicFunc type is an adapter to allow the use of ordinary
// function as Clinic mutator.
type ClinicFunc func(context.Context, *repo.ClinicMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f ClinicFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.ClinicMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.ClinicMutation", m)
}

// The ClinicMemberFunc type is an adapter to allow the use of ordinary
// function as ClinicMember mutator.
type ClinicMemberFunc func(context.Context, *repo.ClinicMemberMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f ClinicMemberFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.ClinicMemberMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.ClinicMemberMutation", m)
}

// The ClinicPermissionFunc type is an adapter to allow the use of ordinary
// function as ClinicPermission mutator.
type ClinicPermissionFunc func(context.Context, *repo.ClinicPermissionMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f ClinicPermissionFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.ClinicPermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.ClinicPermissionMutation", m)
}

// The ClinicSettingsFunc type is an adapter to allow the use of ordinary
// function as ClinicSettings mutator.
type ClinicSettingsFunc func(context.Context, *repo.ClinicSettingsMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f ClinicSettingsFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.ClinicSettingsMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.ClinicSettingsMutation", m)
}

// The CommissionRuleFunc type is an adapter to allow the use of ordinary
// function as CommissionRule mutator.
type CommissionRuleFunc func(context.Context, *repo.CommissionRuleMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f CommissionRuleFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.CommissionRuleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.CommissionRuleMutation", m)
}

// The ContactMessageFunc type is an adapter to allow the use of ordinary
// function as ContactMessage mutator.
type ContactMessageFunc func(context.Context, *repo.ContactMessageMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f ContactMessageFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.ContactMessageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.ContactMessageMutation", m)
}

// The ConversationFunc type is an adapter to allow the use of ordinary
// function as Conversation mutator.
type ConversationFunc func(context.Context, *repo.ConversationMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f ConversationFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.ConversationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.ConversationMutation", m)
}

// The InternPatientAccessFunc type is an adapter to allow the use of ordinary
// function as InternPatientAccess mutator.
type InternPatientAccessFunc func(context.Context, *repo.InternPatientAccessMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f InternPatientAccessFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.InternPatientAccessMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.InternPatientAccessMutation", m)
}

// The InternProfileFunc type is an adapter to allow the use of ordinary
// function as InternProfile mutator.
type InternProfileFunc func(context.Context, *repo.InternProfileMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f InternProfileFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.InternProfileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.InternProfileMutation", m)
}

// The InternTaskFunc type is an adapter to allow the use of ordinary
// function as InternTask mutator.
type InternTaskFunc func(context.Context, *repo.InternTaskMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f InternTaskFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.InternTaskMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.InternTaskMutation", m)
}

// The InternTaskFileFunc type is an adapter to allow the use of ordinary
// function as InternTaskFile mutator.
type InternTaskFileFunc func(context.Context, *repo.InternTaskFileMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f InternTaskFileFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.InternTaskFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.InternTaskFileMutation", m)
}

// The MessageFunc type is an adapter to allow the use of ordinary
// function as Message mutator.
type MessageFunc func(context.Context, *repo.MessageMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f MessageFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.MessageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.MessageMutation", m)
}

// The NotificationFunc type is an adapter to allow the use of ordinary
// function as Notification mutator.
type NotificationFunc func(context.Context, *repo.NotificationMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f NotificationFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.NotificationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.NotificationMutation", m)
}

// The NotificationPrefFunc type is an adapter to allow the use of ordinary
// function as NotificationPref mutator.
type NotificationPrefFunc func(context.Context, *repo.NotificationPrefMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f NotificationPrefFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.NotificationPrefMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.NotificationPrefMutation", m)
}

// The PatientFunc type is an adapter to allow the use of ordinary
// function as Patient mutator.
type PatientFunc func(context.Context, *repo.PatientMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PatientFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PatientMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PatientMutation", m)
}

// The PatientFileFunc type is an adapter to allow the use of ordinary
// function as PatientFile mutator.
type PatientFileFunc func(context.Context, *repo.PatientFileMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PatientFileFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PatientFileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PatientFileMutation", m)
}

// The PatientPrescriptionFunc type is an adapter to allow the use of ordinary
// function as PatientPrescription mutator.
type PatientPrescriptionFunc func(context.Context, *repo.PatientPrescriptionMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PatientPrescriptionFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PatientPrescriptionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PatientPrescriptionMutation", m)
}

// The PatientReportFunc type is an adapter to allow the use of ordinary
// function as PatientReport mutator.
type PatientReportFunc func(context.Context, *repo.PatientReportMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PatientReportFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PatientReportMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PatientReportMutation", m)
}

// The PatientTestFunc type is an adapter to allow the use of ordinary
// function as PatientTest mutator.
type PatientTestFunc func(context.Context, *repo.PatientTestMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PatientTestFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PatientTestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PatientTestMutation", m)
}

// The PaymentRequestFunc type is an adapter to allow the use of ordinary
// function as PaymentRequest mutator.
type PaymentRequestFunc func(context.Context, *repo.PaymentRequestMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PaymentRequestFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PaymentRequestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PaymentRequestMutation", m)
}

// The PsychTestFunc type is an adapter to allow the use of ordinary
// function as PsychTest mutator.
type PsychTestFunc func(context.Context, *repo.PsychTestMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f PsychTestFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.PsychTestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.PsychTestMutation", m)
}

// The RecurringRuleFunc type is an adapter to allow the use of ordinary
// function as RecurringRule mutator.
type RecurringRuleFunc func(context.Context, *repo.RecurringRuleMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f RecurringRuleFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.RecurringRuleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.RecurringRuleMutation", m)
}

// The TherapistProfileFunc type is an adapter to allow the use of ordinary
// function as TherapistProfile mutator.
type TherapistProfileFunc func(context.Context, *repo.TherapistProfileMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f TherapistProfileFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.TherapistProfileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.TherapistProfileMutation", m)
}

// The TicketFunc type is an adapter to allow the use of ordinary
// function as Ticket mutator.
type TicketFunc func(context.Context, *repo.TicketMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f TicketFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.TicketMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.TicketMutation", m)
}

// The TicketMessageFunc type is an adapter to allow the use of ordinary
// function as TicketMessage mutator.
type TicketMessageFunc func(context.Context, *repo.TicketMessageMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f TicketMessageFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.TicketMessageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.TicketMessageMutation", m)
}

// The TimeSlotFunc type is an adapter to allow the use of ordinary
// function as TimeSlot mutator.
type TimeSlotFunc func(context.Context, *repo.TimeSlotMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f TimeSlotFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.TimeSlotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.TimeSlotMutation", m)
}

// The TransactionFunc type is an adapter to allow the use of ordinary
// function as Transaction mutator.
type TransactionFunc func(context.Context, *repo.TransactionMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f TransactionFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.TransactionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.TransactionMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *repo.UserMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.UserMutation", m)
}

// The UserDeviceFunc type is an adapter to allow the use of ordinary
// function as UserDevice mutator.
type UserDeviceFunc func(context.Context, *repo.UserDeviceMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f UserDeviceFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.UserDeviceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.UserDeviceMutation", m)
}

// The UserSessionFunc type is an adapter to allow the use of ordinary
// function as UserSession mutator.
type UserSessionFunc func(context.Context, *repo.UserSessionMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f UserSessionFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.UserSessionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.UserSessionMutation", m)
}

// The WalletFunc type is an adapter to allow the use of ordinary
// function as Wallet mutator.
type WalletFunc func(context.Context, *repo.WalletMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f WalletFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.WalletMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.WalletMutation", m)
}

// The WithdrawalRequestFunc type is an adapter to allow the use of ordinary
// function as WithdrawalRequest mutator.
type WithdrawalRequestFunc func(context.Context, *repo.WithdrawalRequestMutation) (repo.Value, error)

// Mutate calls f(ctx, m).
func (f WithdrawalRequestFunc) Mutate(ctx context.Context, m repo.Mutation) (repo.Value, error) {
	if mv, ok := m.(*repo.WithdrawalRequestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *repo.WithdrawalRequestMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, repo.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m repo.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m repo.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m repo.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op repo.Op) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m repo.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk repo.Hook, cond Condition) repo.Hook {
	return func(next repo.Mutator) repo.Mutator {
		return repo.MutateFunc(func(ctx context.Context, m repo.Mutation) (repo.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, repo.Delete|repo.Create)
func On(hk repo.Hook, op repo.Op) repo.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, repo.Update|repo.UpdateOne)
func Unless(hk repo.Hook, op repo.Op) repo.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) repo.Hook {
	return func(repo.Mutator) repo.Mutator {
		return repo.MutateFunc(func(context.Context, repo.Mutation) (repo.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []repo.Hook {
//		return []repo.Hook{
//			Reject(repo.Delete|repo.Update),
//		}
//	}
func Reject(op repo.Op) repo.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []repo.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...repo.Hook) Chain {
	return Chain{append([]repo.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() repo.Hook {
	return func(mutator repo.Mutator) repo.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...repo.Hook) Chain {
	newHooks := make([]repo.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
