// Code generated by ent, DO NOT EDIT.

package withdrawalrequest

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Alijeyrad/simorq_backend/internal/repo/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// WalletID applies equality check predicate on the "wallet_id" field. It's identical to WalletIDEQ.
func WalletID(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldWalletID, v))
}

// ClinicID applies equality check predicate on the "clinic_id" field. It's identical to ClinicIDEQ.
func ClinicID(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldClinicID, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldAmount, v))
}

// IbanEncrypted applies equality check predicate on the "iban_encrypted" field. It's identical to IbanEncryptedEQ.
func IbanEncrypted(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldIbanEncrypted, v))
}

// AccountHolder applies equality check predicate on the "account_holder" field. It's identical to AccountHolderEQ.
func AccountHolder(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldAccountHolder, v))
}

// BankRef applies equality check predicate on the "bank_ref" field. It's identical to BankRefEQ.
func BankRef(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldBankRef, v))
}

// RequestedAt applies equality check predicate on the "requested_at" field. It's identical to RequestedAtEQ.
func RequestedAt(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldRequestedAt, v))
}

// ProcessedAt applies equality check predicate on the "processed_at" field. It's identical to ProcessedAtEQ.
func ProcessedAt(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldProcessedAt, v))
}

// FailureReason applies equality check predicate on the "failure_reason" field. It's identical to FailureReasonEQ.
func FailureReason(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldFailureReason, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldCreatedAt, v))
}

// WalletIDEQ applies the EQ predicate on the "wallet_id" field.
func WalletIDEQ(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldWalletID, v))
}

// WalletIDNEQ applies the NEQ predicate on the "wallet_id" field.
func WalletIDNEQ(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldWalletID, v))
}

// WalletIDIn applies the In predicate on the "wallet_id" field.
func WalletIDIn(vs ...uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldWalletID, vs...))
}

// WalletIDNotIn applies the NotIn predicate on the "wallet_id" field.
func WalletIDNotIn(vs ...uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldWalletID, vs...))
}

// ClinicIDEQ applies the EQ predicate on the "clinic_id" field.
func ClinicIDEQ(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldClinicID, v))
}

// ClinicIDNEQ applies the NEQ predicate on the "clinic_id" field.
func ClinicIDNEQ(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldClinicID, v))
}

// ClinicIDIn applies the In predicate on the "clinic_id" field.
func ClinicIDIn(vs ...uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldClinicID, vs...))
}

// ClinicIDNotIn applies the NotIn predicate on the "clinic_id" field.
func ClinicIDNotIn(vs ...uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldClinicID, vs...))
}

// ClinicIDGT applies the GT predicate on the "clinic_id" field.
func ClinicIDGT(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldClinicID, v))
}

// ClinicIDGTE applies the GTE predicate on the "clinic_id" field.
func ClinicIDGTE(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldClinicID, v))
}

// ClinicIDLT applies the LT predicate on the "clinic_id" field.
func ClinicIDLT(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldClinicID, v))
}

// ClinicIDLTE applies the LTE predicate on the "clinic_id" field.
func ClinicIDLTE(v uuid.UUID) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldClinicID, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v int64) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldStatus, vs...))
}

// IbanEncryptedEQ applies the EQ predicate on the "iban_encrypted" field.
func IbanEncryptedEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldIbanEncrypted, v))
}

// IbanEncryptedNEQ applies the NEQ predicate on the "iban_encrypted" field.
func IbanEncryptedNEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldIbanEncrypted, v))
}

// IbanEncryptedIn applies the In predicate on the "iban_encrypted" field.
func IbanEncryptedIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldIbanEncrypted, vs...))
}

// IbanEncryptedNotIn applies the NotIn predicate on the "iban_encrypted" field.
func IbanEncryptedNotIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldIbanEncrypted, vs...))
}

// IbanEncryptedGT applies the GT predicate on the "iban_encrypted" field.
func IbanEncryptedGT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldIbanEncrypted, v))
}

// IbanEncryptedGTE applies the GTE predicate on the "iban_encrypted" field.
func IbanEncryptedGTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldIbanEncrypted, v))
}

// IbanEncryptedLT applies the LT predicate on the "iban_encrypted" field.
func IbanEncryptedLT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldIbanEncrypted, v))
}

// IbanEncryptedLTE applies the LTE predicate on the "iban_encrypted" field.
func IbanEncryptedLTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldIbanEncrypted, v))
}

// IbanEncryptedContains applies the Contains predicate on the "iban_encrypted" field.
func IbanEncryptedContains(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContains(FieldIbanEncrypted, v))
}

// IbanEncryptedHasPrefix applies the HasPrefix predicate on the "iban_encrypted" field.
func IbanEncryptedHasPrefix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasPrefix(FieldIbanEncrypted, v))
}

// IbanEncryptedHasSuffix applies the HasSuffix predicate on the "iban_encrypted" field.
func IbanEncryptedHasSuffix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasSuffix(FieldIbanEncrypted, v))
}

// IbanEncryptedEqualFold applies the EqualFold predicate on the "iban_encrypted" field.
func IbanEncryptedEqualFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEqualFold(FieldIbanEncrypted, v))
}

// IbanEncryptedContainsFold applies the ContainsFold predicate on the "iban_encrypted" field.
func IbanEncryptedContainsFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContainsFold(FieldIbanEncrypted, v))
}

// AccountHolderEQ applies the EQ predicate on the "account_holder" field.
func AccountHolderEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldAccountHolder, v))
}

// AccountHolderNEQ applies the NEQ predicate on the "account_holder" field.
func AccountHolderNEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldAccountHolder, v))
}

// AccountHolderIn applies the In predicate on the "account_holder" field.
func AccountHolderIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldAccountHolder, vs...))
}

// AccountHolderNotIn applies the NotIn predicate on the "account_holder" field.
func AccountHolderNotIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldAccountHolder, vs...))
}

// AccountHolderGT applies the GT predicate on the "account_holder" field.
func AccountHolderGT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldAccountHolder, v))
}

// AccountHolderGTE applies the GTE predicate on the "account_holder" field.
func AccountHolderGTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldAccountHolder, v))
}

// AccountHolderLT applies the LT predicate on the "account_holder" field.
func AccountHolderLT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldAccountHolder, v))
}

// AccountHolderLTE applies the LTE predicate on the "account_holder" field.
func AccountHolderLTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldAccountHolder, v))
}

// AccountHolderContains applies the Contains predicate on the "account_holder" field.
func AccountHolderContains(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContains(FieldAccountHolder, v))
}

// AccountHolderHasPrefix applies the HasPrefix predicate on the "account_holder" field.
func AccountHolderHasPrefix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasPrefix(FieldAccountHolder, v))
}

// AccountHolderHasSuffix applies the HasSuffix predicate on the "account_holder" field.
func AccountHolderHasSuffix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasSuffix(FieldAccountHolder, v))
}

// AccountHolderEqualFold applies the EqualFold predicate on the "account_holder" field.
func AccountHolderEqualFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEqualFold(FieldAccountHolder, v))
}

// AccountHolderContainsFold applies the ContainsFold predicate on the "account_holder" field.
func AccountHolderContainsFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContainsFold(FieldAccountHolder, v))
}

// BankRefEQ applies the EQ predicate on the "bank_ref" field.
func BankRefEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldBankRef, v))
}

// BankRefNEQ applies the NEQ predicate on the "bank_ref" field.
func BankRefNEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldBankRef, v))
}

// BankRefIn applies the In predicate on the "bank_ref" field.
func BankRefIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldBankRef, vs...))
}

// BankRefNotIn applies the NotIn predicate on the "bank_ref" field.
func BankRefNotIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldBankRef, vs...))
}

// BankRefGT applies the GT predicate on the "bank_ref" field.
func BankRefGT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldBankRef, v))
}

// BankRefGTE applies the GTE predicate on the "bank_ref" field.
func BankRefGTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldBankRef, v))
}

// BankRefLT applies the LT predicate on the "bank_ref" field.
func BankRefLT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldBankRef, v))
}

// BankRefLTE applies the LTE predicate on the "bank_ref" field.
func BankRefLTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldBankRef, v))
}

// BankRefContains applies the Contains predicate on the "bank_ref" field.
func BankRefContains(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContains(FieldBankRef, v))
}

// BankRefHasPrefix applies the HasPrefix predicate on the "bank_ref" field.
func BankRefHasPrefix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasPrefix(FieldBankRef, v))
}

// BankRefHasSuffix applies the HasSuffix predicate on the "bank_ref" field.
func BankRefHasSuffix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasSuffix(FieldBankRef, v))
}

// BankRefIsNil applies the IsNil predicate on the "bank_ref" field.
func BankRefIsNil() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIsNull(FieldBankRef))
}

// BankRefNotNil applies the NotNil predicate on the "bank_ref" field.
func BankRefNotNil() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotNull(FieldBankRef))
}

// BankRefEqualFold applies the EqualFold predicate on the "bank_ref" field.
func BankRefEqualFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEqualFold(FieldBankRef, v))
}

// BankRefContainsFold applies the ContainsFold predicate on the "bank_ref" field.
func BankRefContainsFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContainsFold(FieldBankRef, v))
}

// RequestedAtEQ applies the EQ predicate on the "requested_at" field.
func RequestedAtEQ(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldRequestedAt, v))
}

// RequestedAtNEQ applies the NEQ predicate on the "requested_at" field.
func RequestedAtNEQ(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldRequestedAt, v))
}

// RequestedAtIn applies the In predicate on the "requested_at" field.
func RequestedAtIn(vs ...time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldRequestedAt, vs...))
}

// RequestedAtNotIn applies the NotIn predicate on the "requested_at" field.
func RequestedAtNotIn(vs ...time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldRequestedAt, vs...))
}

// RequestedAtGT applies the GT predicate on the "requested_at" field.
func RequestedAtGT(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldRequestedAt, v))
}

// RequestedAtGTE applies the GTE predicate on the "requested_at" field.
func RequestedAtGTE(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldRequestedAt, v))
}

// RequestedAtLT applies the LT predicate on the "requested_at" field.
func RequestedAtLT(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldRequestedAt, v))
}

// RequestedAtLTE applies the LTE predicate on the "requested_at" field.
func RequestedAtLTE(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldRequestedAt, v))
}

// ProcessedAtEQ applies the EQ predicate on the "processed_at" field.
func ProcessedAtEQ(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldProcessedAt, v))
}

// ProcessedAtNEQ applies the NEQ predicate on the "processed_at" field.
func ProcessedAtNEQ(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldProcessedAt, v))
}

// ProcessedAtIn applies the In predicate on the "processed_at" field.
func ProcessedAtIn(vs ...time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldProcessedAt, vs...))
}

// ProcessedAtNotIn applies the NotIn predicate on the "processed_at" field.
func ProcessedAtNotIn(vs ...time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldProcessedAt, vs...))
}

// ProcessedAtGT applies the GT predicate on the "processed_at" field.
func ProcessedAtGT(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldProcessedAt, v))
}

// ProcessedAtGTE applies the GTE predicate on the "processed_at" field.
func ProcessedAtGTE(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldProcessedAt, v))
}

// ProcessedAtLT applies the LT predicate on the "processed_at" field.
func ProcessedAtLT(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldProcessedAt, v))
}

// ProcessedAtLTE applies the LTE predicate on the "processed_at" field.
func ProcessedAtLTE(v time.Time) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldProcessedAt, v))
}

// ProcessedAtIsNil applies the IsNil predicate on the "processed_at" field.
func ProcessedAtIsNil() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIsNull(FieldProcessedAt))
}

// ProcessedAtNotNil applies the NotNil predicate on the "processed_at" field.
func ProcessedAtNotNil() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotNull(FieldProcessedAt))
}

// FailureReasonEQ applies the EQ predicate on the "failure_reason" field.
func FailureReasonEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEQ(FieldFailureReason, v))
}

// FailureReasonNEQ applies the NEQ predicate on the "failure_reason" field.
func FailureReasonNEQ(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNEQ(FieldFailureReason, v))
}

// FailureReasonIn applies the In predicate on the "failure_reason" field.
func FailureReasonIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIn(FieldFailureReason, vs...))
}

// FailureReasonNotIn applies the NotIn predicate on the "failure_reason" field.
func FailureReasonNotIn(vs ...string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotIn(FieldFailureReason, vs...))
}

// FailureReasonGT applies the GT predicate on the "failure_reason" field.
func FailureReasonGT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGT(FieldFailureReason, v))
}

// FailureReasonGTE applies the GTE predicate on the "failure_reason" field.
func FailureReasonGTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldGTE(FieldFailureReason, v))
}

// FailureReasonLT applies the LT predicate on the "failure_reason" field.
func FailureReasonLT(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLT(FieldFailureReason, v))
}

// FailureReasonLTE applies the LTE predicate on the "failure_reason" field.
func FailureReasonLTE(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldLTE(FieldFailureReason, v))
}

// FailureReasonContains applies the Contains predicate on the "failure_reason" field.
func FailureReasonContains(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContains(FieldFailureReason, v))
}

// FailureReasonHasPrefix applies the HasPrefix predicate on the "failure_reason" field.
func FailureReasonHasPrefix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasPrefix(FieldFailureReason, v))
}

// FailureReasonHasSuffix applies the HasSuffix predicate on the "failure_reason" field.
func FailureReasonHasSuffix(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldHasSuffix(FieldFailureReason, v))
}

// FailureReasonIsNil applies the IsNil predicate on the "failure_reason" field.
func FailureReasonIsNil() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldIsNull(FieldFailureReason))
}

// FailureReasonNotNil applies the NotNil predicate on the "failure_reason" field.
func FailureReasonNotNil() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldNotNull(FieldFailureReason))
}

// FailureReasonEqualFold applies the EqualFold predicate on the "failure_reason" field.
func FailureReasonEqualFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldEqualFold(FieldFailureReason, v))
}

// FailureReasonContainsFold applies the ContainsFold predicate on the "failure_reason" field.
func FailureReasonContainsFold(v string) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.FieldContainsFold(FieldFailureReason, v))
}

// HasWallet applies the HasEdge predicate on the "wallet" edge.
func HasWallet() predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, WalletTable, WalletColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasWalletWith applies the HasEdge predicate on the "wallet" edge with a given conditions (other predicates).
func HasWalletWith(preds ...predicate.Wallet) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(func(s *sql.Selector) {
		step := newWalletStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.WithdrawalRequest) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.WithdrawalRequest) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.WithdrawalRequest) predicate.WithdrawalRequest {
	return predicate.WithdrawalRequest(sql.NotPredicates(p))
}
